- cwltool/draft2tool.py
- cwltool/process.py
- cwltool/workflow.py
cwltool implementation of https://github.com/common-workflow-language/common-workflow-language/pull/159
> Shell commands

- cwltool/cwltest.py
- cwltool/main.py
The patch adds a one-line description as it would appear behind
the name of a yet non-existing man page. This is meant to eventually
help auto-creating it/them.
> Improving expressiveness of parser --help

- cwltool/job.py
- cwltool/main.py
This allows user to opt to enable network for docker container. 
r? @tetron
> feat(docker-net): add option to allow using default network

- cwltool/cwltest.py
> Improved error handling in cwltest.py.

- cwltool/cwltest.py
draft-2/draft-3 tests against v1.0 runners.
> Copy location to path for cwltest comparison to support running draft

- cwltool/main.py
> Fixing 'path' -> 'location' issue

- cwltool/cwltest.py
- cwltool/draft2tool.py
- cwltool/main.py
- cwltool/process.py
Pass factory object that takes relative reference basedir instead of actual FsAccess object.
> Refactor fs_access abstraction

- cwltool/cwltest.py
Now exit code 0 when there are unsupported features but no failures.
> Improve cwltest to handle keyboard interrupt.  

- cwltool/builder.py
- cwltool/main.py
Also handle Directory[] in generate_parser.
> Fix serializing Directory[] on command line. 

- cwltool/draft2tool.py
- cwltool/load_tool.py
- cwltool/pathmapper.py
- cwltool/process.py
- cwltool/sandboxjs.py
produced by expression tool in output.
> Correctly handle file and directory literals 

- cwltool_module.Dockerfile
- ez_setup.py
- setup.py
Fixes https://github.com/common-workflow-language/cwltool/issues/216
> add dependency on setuptools for html5lib

- README.rst
> typo: instal -> install

- cwltool/draft2tool.py
- cwltool/workflow.py
- tests/wf/echo.cwl
- tests/wf/scatterfail.cwl
- tests/wf/wffail.cwl
- tox.ini
> When on_error=continue, do not execute downstream steps connected to an

- MANIFEST.in
- cwltool_module.Dockerfile
Follow up from #292 Thanks to @mr-c and @tetron
> Remove ez_setup from conformance test Docker

- cwltool/cwlNodeEngine.js
- cwltool/sandboxjs.py
Don't get confused by different program also called "node".
Also improve reading/writing pipes.
> Improve detection of Node.js

- requirements.txt
- setup.py
- tests/test_examples.py
- tox.ini
Add basic sanity check for --print-dot.
> Bump schema salad pin.  Pin mypy version.  

- cwltool/extensions.yml
- cwltool/process.py
- requirements.txt
- setup.py
- tests/wf/listing_none.cwl
- tests/wf/listing_shallow.cwl
Extensions should not be a keyword.
Depends on https://github.com/common-workflow-language/schema_salad/pull/97
> Mark LoadListing as not in vocab so it must be fully qualified 

- README.rst
> docs: readme.rst: better parsing of hyperlink

- cwltool/pack.py
> --pack generates same-file $import to reference shared objects 

- cwltool/builder.py
- cwltool/draft2tool.py
- cwltool/job.py
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/pathmapper.py
- cwltool/process.py
- tests/test_check.py
- tests/test_pack.py
- tests/wf/badout1.cwl
- tests/wf/badout2.cwl
- tests/wf/badout3.cwl
Also verify that files are files and directories are directories (according to isfile() and isdir())
> Validate that output files actually exist

- setup.py
Closes https://github.com/common-workflow-language/cwltool/issues/392
> feat: prevent python3-pip installation until py3 is supported

- cwltool/pathmapper.py
- tests/test_examples.py
- tests/test_pathmapper.py
Here's the cleaner PR to fix https://github.com/common-workflow-language/cwltool/issues/268
Obsoletes https://github.com/common-workflow-language/cwltool/pull/338
> Generate nameroot and nameext from basename

- cwltool/main.py
- cwltool/workflow.py
- mypy.ini
- requirements.txt
- setup.py
set upper bound for ruamel.yaml version, 
same as in schema_salad: https://github.com/common-workflow-language/schema_salad/blob/master/setup.py#L33
> setup.py: pin ruamel.yaml package version

- cwltool/draft2tool.py
Special thanks @maitai for pair programming this with me!
> use checksum instead of modification time for caching, if available

- cwltool/process.py
- tox.ini
https://mypy-lang.blogspot.in/2017/07/mypy-0520-released.html
> upgrade mypy to v.520

- appveyor.yml
start python 3 tests on appveyor
Closes: https://github.com/common-workflow-language/cwltool/issues/500
> Python3windows

- README.rst
Closes https://github.com/common-workflow-language/cwltool/issues/401
> README: Fix linting and minor errors

- cwltool/load_tool.py
- tests/test_pack.py
- tests/wf/wc-job.json
- tests/wf/whale.txt
> Run "#main" resolved object by default

- cwltool/job.py
> fix broken job.json and job script file writing

- README.rst
Waiting on the regressions with quoting to be fixed..
> [WIP] add udocker example

- cwltool/job.py
> Fix writable directories staging

- tests/override/echo.cwl
- tests/test_override.py
> Drop "-n" from echo command in test-override to make it portable

- tests/test_js_sandbox.py
- tests/test_parallel.py
@anton-khodak Can you assist with this error?
(you can test locally via `./release-test.sh`)
```
________________________________________________________ TestParallel.test_sequential_workflow ________________________________________________________
raise self.makeError("\n".join(traceback.format_exception(exc_type, exc_value, tb)))
ValidationException: Traceback (most recent call last):
File "/home/mcrusoe/cwltool/testenv1/local/lib/python2.7/site-packages/cwltool/pathmapper.py", line 263, in visit
st = os.lstat(deref)
OSError: [Errno 2] No such file or directory: '/home/mcrusoe/cwltool/testenv1/not-cwltool/tests/wf/whale.txt'
workflow.py                497 ERROR    [step step1_11] Cannot make job: Traceback (most recent call last):
File …
```
> Fix the release

- cwltool/executors.py
- cwltool/process.py
Obviates need for https://github.com/reanahub/reana-workflow-engine-cwl/pull/25 or other changes
> add default value for compute_checksum

- cwltool/docker.py
- cwltool/extensions.yml
- cwltool/job.py
- cwltool/main.py
- cwltool/process.py
- cwltool/secrets.py
- tests/test_secrets.py
- tests/wf/secret_job.cwl
- tests/wf/secret_wf.cwl
These are string input parameters that represent sensitive information
such as passwords.  This feature deliberately obscures them by
replacing them with a placeholder during workflow evaluation and then
substituting the real value at the last moment.
> Experimental extension for "secret" parameters.

- cwltool/validate_js.py
> Suppress spurious "invalid fields `name`" warnings

- README.rst
- tox.ini
This is done passing arguments from tox to pytest, so other options might become available too.
Also added instruction on how to select a specific test
> feature: allow users to run specific tests using tox

- cwltool/builder.py
- cwltool/executors.py
> Improve error reporting of file format errors.

- cwltool/resolver.py
- cwltool/singularity.py
- requirements.txt
- setup.py
- tox.ini
Bonus: fixes the execution of two conformance tests.
> Tighten our use of Singularity

- cwltool/singularity.py
Be explicit that `docker{File,Load,Import}` is not yet supported
Add support for --docker-force-pull
When checking for cached Singularity image, also try the normalized version of
the provided dockerImageId
> Clean up Singularity support

- appveyor.yml
- cwltool/expression.py
- cwltool/main.py
- cwltool/process.py
- cwltool/utils.py
> Fill in sizes for files inside directories only if needed

- appveyor.yml
- cwltool/singularity.py
> Fix checking the cwd for singularity images

- Makefile
- appveyor.yml
- cwltool/process.py
- tests/test_fetch.py
Fixes https://github.com/common-workflow-language/cwltool/issues/760
> ensure that default `File`s have sizes

- cwltool/builder.py
Part of https://github.com/common-workflow-language/cwltool/pull/731 but ready for merging now
> still eval even if optional + null

- cwltool/argparser.py
- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/job.py
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/process.py
- cwltool/workflow.py
- tests/test_fetch.py
Can provide custom loadingContext/runtimeContext.
> Simplify interface of main()

- cwltool/validate_js.py
Fixes https://github.com/EBI-Metagenomics/ebi-metagenomics-cwl/issues/77
> remove erroneous assert

- README.rst
(First contribution here: Apologies if this isn't the right direction.)
> small typos in README

- cwltool/docker.py
- cwltool/factory.py
- cwltool/main.py
- cwltool/software_requirements.py
- tests/test_examples.py
- tests/test_parallel.py
- tests/util.py
- tests/wf/count-lines1-wf.cwl
- tests/wf/scatter-wf4.cwl
Also normalizes the Factory() interface by removing the use of kwargs
> Windows fixes

- cwltool/argparser.py
- cwltool/context.py
- cwltool/docker.py
and some general cleanups of `cwltool/docker.py`
> add --strict-memory-limit

- Makefile
- cwltool/docker.py
- tests/test_examples.py
> Fix container ID recording 

- cwltool/command_line_tool.py
- cwltool/job.py
- cwltool/workflow.py
Two conformance tests will still crash for me if I run with both `--cache cache_dir` and `--parallel` and a high `-j` level (multi-testing) to `run_tests.sh`
> Cache improvements

- cwltool/workflow.py
Fixes https://github.com/common-workflow-language/cwltool/issues/846
> WorkflowStepInput.valueFrom: populate Directory.listing

- appveyor.yml
Force codecov to collect coverage.xml in appveyor
> Enable code coverage reporting in appveyor

- setup.py
- test-requirements.txt
- tests/test_check.py
- tests/test_cwl_version.py
- tests/test_default_path.py
- tests/test_dependencies.py
- tests/test_docker_warning.py
- tests/test_examples.py
- tests/test_ext.py
- tests/test_fetch.py
- tests/test_http_input.py
- tests/test_iwdr.py
- tests/test_js_sandbox.py
- tests/test_override.py
- tests/test_pack.py
- tests/test_parallel.py
- tests/test_pathmapper.py
- tests/test_provenance.py
- tests/test_rdfprint.py
- tests/test_relax_path_checks.py
- tests/test_secrets.py
- tests/test_toolargparse.py
- tests/test_validate_js.py
- tests/util.py
Removes the dependency from tests as per #885
Also cleans up some code by parametrizing tests
> Remove unittest dependency

- cwltool/process.py
- tests/test_deps_env/random-lines/1.0/scripts/random-lines
Follow on to https://github.com/common-workflow-language/cwltool/pull/894
> make the other checksums streaming safe too

- setup.py
> fix ruamel version

- cwltool/docker.py
- cwltool/process.py
- tests/test_relocate.py
- tests/wf/910.cwl
As shown in #910 it fails on certain cases
> Fix folder relocations on existing folders

- cwltool/main.py
> catch and explain invalid input object

- gittaggers.py
Finally! Thanks to @portah for nudging me on this
> make compatible with setuptools > 40.0.0

- gittaggers.py
Fixes https://github.com/common-workflow-language/cwltool/issues/952
> support older setuptools

- tests/test_empty_input.py
- tests/test_toolargparse.py
- tests/util.py
- tests/wf/no-parameters-echo.cwl
> Test against errors on empty input from stdin

- cwltool/argparser.py
- cwltool/context.py
- cwltool/docker.py
- tests/test_examples.py
Regression fix: prevents the creation of `20181113043853-303248.cid` files by default
> fix cid default bug

- tests/test_provenance.py
- tests/wf/expect_packed.cwl
- tests/wf/revsort-job.json
- tests/wf/revsort.cwl
- tests/wf/revtool.cwl
- tests/wf/sorttool.cwl
Makes debugging the workflow easier to the eyes
> Rename revtool labels

- MANIFEST.in
Includes the license in the pypi source distribution.
> include license in source distribution

- cwltool/argparser.py
- cwltool/context.py
- cwltool/docker.py
- cwltool/job.py
- cwltool/main.py
- cwltool/singularity.py
- cwltool/utils.py
- cwltool/validate_js.py
- tests/test_docker_info.py
- tests/test_examples.py
- tests/wf/missing-tool.cwl
- tests/wf/timelimit-fail.cwl
- tests/wf/timelimit.cwl
This works, but fails on TravisCI due to the single core allocated.
> Measure Docker container memory usage

- cwltool/docker.py
Fix for https://github.com/common-workflow-language/cwltool/issues/1043
> Ensure subdirectory exists for staging

- cwltool/command_line_tool.py
Should not be affected by the loadContents limit.
> Fix regression in compute checksum.

- Makefile
- appveyor.yml
- setup.py
- test-requirements.txt
> Fix the build due to galaxy-lib & pytest breakage

- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/update.py
- tests/secondary-files-string-v1.cwl
- tests/test_examples.py
Fixes https://github.com/common-workflow-language/cwltool/issues/1110
> Fix secondaryFile as single string/expression in CWL1.0

- cwltool/command_line_tool.py
- tests/test_examples.py
- tests/wf/optional-numerical-output-0.cwl
Fix for https://github.com/common-workflow-language/cwltool/issues/1121
> Don't convert 0 to null on optional output

- cwltool/__init__.py
- cwltool/main.py
- setup.py
Discussion at https://github.com/common-workflow-language/cwltool/issues/1107
> publicize end of life for cwltool on Python 2.7

- cwltool/job.py
- release-test.sh
- tests/env.cwl
- tests/test_examples.py
Whoops, we were preserving the all the environment variables by default!!
> Over env preservation

- .travis.yml
- Makefile
- cwltool/job.py
- release-test.sh
- tests/test_examples.py
- tests/test_udocker.py
Improve udocker test install reliability
udocker: pull before execution so that ToolTimeLimit isn't affected
> Don't run release test separately

- cwltool/singularity.py
> singularity: if dockerImageId is a local file, use it

- README.rst
> Try out the new badges

- requirements.txt
- setup.py
due to https://github.com/PythonCharmers/python-future/issues/213
> set minimum version of future

- cwltool/procgenerator.py
- cwltool/workflow.py
> schema_salad.validate.indent -> sourceline.indent

- cwltool/argparser.py
- cwltool/validate_js.py
- requirements.txt
- setup.py
- tox.ini
> max ruamel.yaml is 0.16.5; update mypy

- cwltool/pack.py
- tests/test_pack.py
- tests/wf/expect_trick_packed.cwl
- tests/wf/trick_revsort.cwl
> pack: allow inputs/outputs named "name"

- Makefile
- cwltool/main.py
- cwltool/pack.py
- cwltool/update.py
- tests/test_pack.py
Ensures that all the document loading options get passed through.
> Pass loadingContext to pack().

- cwltool/docker.py
> Fixed typo in docker.py -  should be in instead of is

- MANIFEST.in
- cwltool/job.py
- cwltool/update.py
- tests/iwdr_dir_literal_real_file.cwl
- tests/test_iwdr.py
> cope with unmovable files left over from Docker+IWDR

- cwltool/argparser.py
- cwltool/command_line_tool.py
- cwltool/udocker.py
- tests/test_examples.py
- tests/test_udocker.py
> fix udocker

- cwltool/argparser.py
> Don't enable color output by default on MS Windows

- .travis.yml
- CONTRIBUTING.md
- README.rst
- appveyor.yml
- requirements.txt
- setup.py
- tox.ini
> Drop support/testing/CI for Python 3.5

- cwltool/builder.py
- cwltool/context.py
- cwltool/docker.py
- cwltool/executors.py
- cwltool/expression.py
- cwltool/main.py
- cwltool/process.py
- cwltool/singularity.py
A bit brutal. Maybe at some point we should assume there are no opaque resource specifications?
> support opaque resources

- requirements.txt
> add argcomplete to requirements

- cwltool/__init__.py
- cwltool/load_tool.py
- cwltool/main.py
- requirements.txt
- setup.py
- tests/test_content_type.py
- tests/test_fetch.py
- tests/test_iwdr.py
- tests/test_provenance.py
- tests/test_relax_path_checks.py
- tests/test_toolargparse.py
- tests/test_trs.py
- tests/test_udocker.py
- tests/util.py
requires https://github.com/common-workflow-language/schema_salad/pull/377
> Try to detect if we got a bad URL for the job object 

- cwltool/process.py
- tests/test_examples.py
- tests/wc-tool-bad-hints.cwl
- tests/wc-tool-bad-reqs.cwl
> check for empty hints/reqs

- .coveragerc
- .github/workflows/ci-tests.yml
- Makefile
- README.rst
- conformance-test.sh
- cwltool/argparser.py
- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/docker.py
- cwltool/env_to_stdout.py
- cwltool/job.py
- cwltool/run_job.py
- cwltool/singularity.py
- cwltool/software_requirements.py
- tests/env3.cwl
- tests/env4.cwl
- tests/env_with_software_req.yml
- tests/test_dependencies.py
- tests/test_deps_env/modulefiles/random-lines/1.0
- tests/test_environment.py
- tests/test_singularity.py
- tests/util.py
A very first attempt at the fix I proposed in #1377 
This now works for a the single test case on that issue. I'd like feedback before trying to do it more properly.
Thanks!
TODO:
> WIP: fix interaction of software requirements and environments

- requirements.txt
- setup.py
To include the fix from https://github.com/common-workflow-language/schema_salad/issues/385
> update minimum required version of schema_salad

- cwltool/argparser.py
- cwltool/job.py
- cwltool/main.py
- cwltool/subgraph.py
- tests/test_environment.py
- tests/test_singularity.py
- tests/util.py
Fixes #1443  ; added `--single-process` to match @jdidion 's specific need
> --single-step: fix typo ; add --single-process

- requirements.txt
- setup.py
> skip psutil 5.6.1

- cwltool/builder.py
- cwltool/checker.py
- cwltool/cwlrdf.py
- cwltool/expression.py
- cwltool/job.py
- cwltool/load_tool.py
- cwltool/provenance.py
- cwltool/update.py
- cwltool/utils.py
- tests/test_examples.py
via `make pyupgrade` , with some `TypedDict`→new classes changes reverted due to personal taste.
> upgrade to Python 3.6+ syntax

- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/expression.py
- cwltool/process.py
- cwltool/validate_js.py
- requirements.txt
- setup.py
- tests/test_procgenerator.py
- tests/test_validate_js.py
- tests/wf/generator/pytoolgen.cwl
Specifically https://github.com/common-workflow-language/schema_salad/pull/408
Arvados-DCO-1.1-Signed-off-by: Peter Amstutz <peter.amstutz@curii.com>
> Update schema-salad dependency for bug fix

- cwltool/expression.py
- tests/test_examples.py
- tests/wf/paramref_arguments_self.cwl
> CommandLineTool.arguments: correctly set $(self)

- tox.ini
See https://github.com/PyCQA/bandit/issues/730#issuecomment-907764680
> skip broken version of importlib_metadata

- conformance-test.sh
- cwltool/singularity.py
- tests/test_environment.py
Fixes #1441
Also https://github.com/hpcng/singularity/issues/1607 was fixed, so revert our workaround for sufficiently recent versions of singularity
> fix add_file_or_directory_volume for singularity

- Makefile
- cwltool/subgraph.py
- tests/subgraph/1432.cwl
- tests/subgraph/extract_step2_1432.json
- tests/test_subgraph.py
- tests/test_validate_js.py
> subgraph: support long version of WorkflowStep[].out

- tests/test_examples.py
- tox.ini
> parallelize all test execution

- cwltool/workflow.py
- tests/test_examples.py
- tests/wf/811.cwl
- tests/wf/811_inputs.yml
- tests/wf/schemadef-tool.cwl
- tests/wf/schemadef-type.yml
> Fix #811 (SchemaDefRequirements not working in workflows)

- cwltool/pack.py
- tests/test_pack.py
- tests/wf/expect_iwd-passthrough1_packed.cwl
- tests/wf/iwd-passthrough1.cwl
> packing: treat the IDs of the outputs separately

- cwltool/factory.py
- cwltool/main.py
- cwltool/workflow.py
> revert relocation of default_make_tool initialization

- cwltool/main.py
- tests/subgraph/timelimit2-wf.cwl
- tests/test_subgraph.py
> --print-targets: support embedded step processess

- cwltool/main.py
- tests/test_subgraph.py
- tests/wf/double-nested.cwl
Inspired by https://github.com/douglowe/cwl-mutation-example ; thanks @douglowe!
> Fix --print-targets to pass inherited reqs.

- cwltool/load_tool.py
- tests/test_examples.py
- tests/wf/1590.cwl
> expand stdin shortcut even when an ID is preset

- cwltool/executors.py
This reverts commit 88b9cfe1672fe31c52fb6f745b876dbb5c9491a1.
> Revert "Message about using --parallel, and how other CWL runners are available. (#1671)"

- .github/workflows/ci-tests.yml
- build-cwltool-docker.sh
- cwltool.Dockerfile
- mypy-requirements.txt
To fix the cwltool Docker build
> include ruamel.yaml in the mypy reqs & fix/test container build

- cwltool/executors.py
- cwltool/job.py
Thanks to https://github.com/python/typeshed/commit/d7a5a147a0740816b837614c5f8fd429d0b8756e
> remove some psutil type ignores

- setup.py
- test-requirements.txt
- tests/test_dependencies.py
Depends on https://github.com/galaxyproject/galaxy/pull/14528 being merged and a new release being cut
> Add test to catch future regressions in --beta-use-biocontainers

- tests/test_tmpdir.py
I meant to include this in #1674
> test --leave-tmpdir

- lint-requirements.txt
- mypy-requirements.txt
- requirements.txt
- test-requirements.txt
Like `pip install $(grep -v mypy mypy-requirements.txt)`
> *requirements.txt; remove spaces to enable re-use in other contexts

- cwltool/load_tool.py
- cwltool/main.py
- tests/test_examples.py
- tests/wf/input_named_id.cwl
- tests/wf/input_named_id.yaml
> job loading: allow inputs named "id"

- cwltool/singularity.py
Based on the discussion here: https://github.com/common-workflow-language/cwl-utils/pull/342
> Append "_latest" to image id if no tag is present
