common-workflow-language/cwltool

- cwltool/draft2tool.py
- cwltool/job.py
Allow output type: ["null", File]
> Allow output type: ["null", File]

- cwltool/main.py
A consequence of observations on the simplified hello.cwl and https://github.com/common-workflow-language/workflows/pull/60 .
> Do not ask to select from list with single element

- cwltool/draft2tool.py
Handles mapping paths in Docker images and returned through JSON back
to original filesystem paths. Does reverse mapping of inputs as well
as anything in the output directory. Needs to remap at two locations:
before checking for secondaryFiles, and returning the final file
structure.
Fixes common-workflow-language/cwltool#36.
> Reverse map internal run files to original path

- cwltool/draft2tool.py
The step in `CommandLineTool.job` that implicitly maps files in
builder.bindings to container paths via dictionary assignment
misses some cases in complex inputs. The result is that builder.bindings
will have correct internal Docker paths in `valueFrom` but not in `do_eval`,
leading to command line arguments that still reference the external
path.
To fix, this does an explicit `adjustFiles` remapping over all elements
in builder.bindings, supplementing the work done by the implicit call
and ensuring both `builder.files` and `builder.bindings` are
synchronized.
Thanks to @tetron for discussion and pointers on digging into the code
to fix this.
> Ensure full mapping of paths to container

- cwltool/sandboxjs.py
A small fix for 6ce637045 to stop searching for nodejs
implementations when the first is found. This prevents an error
when you have a local nodejs but not the node:slim docker image.
(ref #45 and #39).
> Stop looking for nodejs when found

- cwltool/workflow.py
This is a proposed solution to fix the bug [https://github.com/common-workflow-language/cwltool/issues/53](https://github.com/common-workflow-language/cwltool/issues/53).
> Mapping non_scatter keys to valueFrom fields

- cwltool/job.py
- cwltool/main.py
Instead of `--enable_net` being a boolean, I added the ability to explicitly define the docker network id. If I wanted to use, say, the `host` docker network:
```
cwltool.py --enable-net host ...
```
If you don't use the option is acts just as before.
> feat(docker-net-option): Allows user to define the docker network

- cwltool.py
@tetron I would suggest using this (`cwltool.py`) instead of `cwltool/main.py` to solve the issues Curoverse was having since the move to relative imports.
As a reminder, here is the other workaround:  `setup.py install` or `setup.py develop` and use the `cwltool` that gets install to the appropriate `bin/` directory.
> add convenient entry point for cwltool

- cwltool/draft2tool.py
- cwltool/main.py
- cwltool/pathmapper.py
- cwltool/process.py
Adds `--cachedir`
When enabled, each job computes a hash of the work based on the command line, sizes/time stamps of input files and effective requirements.   The output directory of the job is selected based on this hash.  If the output directory already exists in the cache directory, the work is skipped and the existing output is used.
> Cache jobs

- cwltool/cwltest.py
- cwltool/draft2tool.py
- cwltool/expression.py
- cwltool/job.py
- cwltool/main.py
- cwltool/process.py
- setup.py
> switch to ruamel.yaml, use C loader if available, only load safely

- cwltool/main.py
- tests/test_toolargparse.py
Sequal to https://github.com/common-workflow-language/cwltool/pull/76
> Fix boolean input to argparse

- cwltool/workflow.py
This should fix the issue encountered when a step in a workflow feeds optional arguments to a tool. Example:
__Foo tool:__ 
```
#!/usr/bin/env cwl-runner
cwlVersion: 'cwl:draft-3'
class: CommandLineTool
requirements:
- class: InlineJavascriptRequirement
inputs:
- id: foo
type:
- 'null'
- File
description: foo
outputs:
- id: '#bar'
type: File
outputBinding:
glob: bar_out
stdout: "bar_out"
baseCommand: 
- echo
```
__Workflow using Foo tool:__
```
#!/usr/bin/env cwl-runner
class: Workflow
requirements:
- class: ScatterFeatureRequirement
inputs:
- id: foo_files
type:
type: array
items: File
outputs:
- id: '#bar'
source: "#footool.bar"
type:
type: array
items: File
steps:
- id: "#footool"
run: {import: "tool-test.cwl" }
scatter: "#footool.foo"
inputs:
- id: "#footool.foo"
source: "#foo_files" …
```
> skip null from items when testing same type

- cwltool/draft2tool.py
This fixes so that one can concatenate input paths in the output spec's glob field, with e.g. suffixes, like so (see the .amb, .ann, .bwt, .pac, .se suffixes added):
```yaml
outputs:
- id: output
type: { type: array, items: File }
outputBinding:
glob:
- $(inputs.input.path).amb
- $(inputs.input.path).ann
- $(inputs.input.path).bwt
- $(inputs.input.path).pac
- $(inputs.input.path).sa
```
Previously you would get an error if trying to use inputs.[somthing].path, since it starts with a `/`, which was not allowed, until this change.
For more background, see [this discussion on gitter](https://gitter.im/common-workflow-language/common-workflow-language?at=573348c27df8adaf347d5589):
> Samuel Lampa @samuell 16:59
> Hi, this is a yaml question maybe, but do you know how to concatenate a …
> Enable concatenating input paths with suffix strings

- cwltool/main.py
This allows rerunning of ``main()`` within a single Python application... an application that rhymes with flanemo.
> Restore global logger state modified in main.py.

- cwltool/load_tool.py
- cwltool/main.py
- cwltool/process.py
Use cwltool --pack to combine workflow and all its tools into a single file.
> Add --pack feature

- cwltool/main.py
- cwltool/process.py
this is a fix to the problem described in #101 , with additional modifications to generate the parser correctly if parameters include an enum type.
> implement enum type in cwltool

- cwltool/workflow.py
- tests/test_examples.py
Now properly accomodates unions.  Alternate solution for #85
> Fix type checking that a source port is assignable to a sink port

- cwltool/draft2tool.py
after nameroot/nameext has been added to file objects for use in expressions.
> Bug fix: compute stdout file name 

- cwltool/draft2tool.py
- cwltool/job.py
- cwltool/process.py
Was not correctly propagated from 'entry' to path mapper, and job.py was overwriting the modified output file by accident.
> Fix implementation of writable flag

- README.rst
Looks like a directory name has changed and README instructions for install from source didn't keep up.
> Fix README new directory location cwlref-runner

- cwltool/job.py
I was trying to run the docker example from here:
http://www.commonwl.org/v1.0/UserGuide.html#Running_tools_inside_Docker
I received an error about `Mounts denied.../var/folders...`:
```
[job d.cwl] /var/folders/fs/vv08ppmd1mj7g35hyq5m_7nr0000gp/T/tmp24cwqi$ docker \
run \
-i \
--volume=/Users/jpb67/Documents/work/cwl/hello.js:/var/lib/cwl/stg1e37b475-6862-491a-9dbf-8bae6f590abe/hello.js:ro \
--volume=/var/folders/fs/vv08ppmd1mj7g35hyq5m_7nr0000gp/T/tmp24cwqi:/var/spool/cwl:rw \
--volume=/var/folders/fs/vv08ppmd1mj7g35hyq5m_7nr0000gp/T/tmpLuHuEa:/tmp:rw \
--workdir=/var/spool/cwl \
--read-only=true \
--user=502 \
--rm \
--env=TMPDIR=/tmp \
--env=HOME=/var/spool/cwl \
node:slim \
node \
/var/lib/cwl/stg1e37b475-6862-491a-9dbf-8bae6f590abe/hello.js
docker: Error response from daemon: Mounts …
```
> Tweak to work with Docker OSX Beta

- cwltool/workflow.py
- tests/test_bad_outputs_wf.cwl
- tests/test_examples.py
Must match one of the outputs of the underlying process.
> Add check that workflow step 'out' parameter

- cwltool/process.py
When running on systems where temporary directories have symlinks like
(/scratch -> /myfilesystem/scratch) outdir will end up as /scratch/tmp12345
while the actual output files are in /myfilesystem/scratch/tmp12345
resulting in failures in draft2tool
(https://github.com/common-workflow-language/cwltool/blob/e23bf6ae7b7838cf599445830ab3a69648ed8833/cwltool/draft2tool.py#L98). This normalizes these so paths match correctly.
> Normalize symlinks in out and temp directories

- cwltool/job.py
- cwltool/main.py
This pull request addresses two security issues we have faced when using CWL.
The first is that the `--enable-net` flag never actually worked, in that the network in a docker container was always enabled, even if this flag was not present. It claimed the default behavior was to disable the network, but this was not the case.
In order to not surprise everyone who expects the network to be enabled without passing in a flag, this was changed to `--disable-net`, which disables the network inside a docker container if present.
The other issue was that we want to enforce the use of a docker container (in order to prevent network calls) even if the tool itself doesn't specify one. For this a `--default-container` flag was added that, if present, sets the docker container to run the command in if …
> Allow the disabling of the network inside a docker container, and add the ability to provide a default docker container if one is not specified

- cwltool/builder.py
- cwltool/job.py
- cwltool/process.py
> Add extension point allowing writing up a job script file for tool commands.

- cwltool/job.py
- cwltool/main.py
We're running into an issue where cwltool sets the uid to match the running user overriding the `USER` command https://docs.docker.com/engine/reference/builder/#/user
This pull request proposes an option to disable this setting.
This is further documented at https://github.com/ga4gh/dockstore/issues/475
> Allow disabling matching the container user to the running user

- README.rst
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/resolver.py
Split from #201 while we discuss https://github.com/common-workflow-language/cwltool/pull/201#issuecomment-259643533
> Local resolver

- cwltool/draft2tool.py
- cwltool/main.py
- tests/test_relax_path_checks.py
> add flag to allow for spaces in file names

- cwltool/process.py
Allows for hints originating from $import
Fixes #228
> Strip identifiers when checking hints

- cwltool/main.py
Clean up initialization of args.tmp_outdir_prefix, args.tmpdir_prefix, and args.cachedir.
> Fix --tmp-outdir-prefix for CommandLineTools.  

- cwltool/workflow.py
A workflow step might complete and return output to the workflow state, but previously only creating work was counted as "making progress".  Now receiving output for a step is also considered "making progress" so that it will iterate over the workflow again instead of yielding None.
> Bugfix, workflow receiving step output counts as making progress

- cwltool/draft2tool.py
- cwltool/resolver.py
- cwltool/stdfsaccess.py
- setup.py
Quote hashes in filenames except in special cases, in order to distinguish between hash used as fragment identifier and as part of filename.
> Hashes in filenames

- cwltool/job.py
> Fail if expecting to run in Docker but not available.

- cwltool/main.py
When we run cwltool without any argument we get a "try -h" message. Instead of that directly show Usage message.
> Showing usage message when no arguments are passed 

- cwltool/builder.py
- cwltool/draft2tool.py
- cwltool/extensions.yml
- tests/wf/listing_deep.cwl
- tests/wf/listing_none.cwl
- tests/wf/listing_shallow.cwl
To no_listing, shallow_listing, deep_listing.
> Rename loadListing enum

- cwltool/process.py
If a Directory object lacks a listing field.
> Fix mergedirs() so it doesn't fail

- .github/ISSUE_TEMPLATE.md
This template will automatically show up in write area when creating issues in this repository. 
I've picked this template from ``jinja2`` project and made necessary changes to make it suitable for our project.
> added ISSUE_TEMPLATE.md

- cwltool/workflow.py
from the job() method to the receive_output() method.
This closes a gap whereby sometimes all steps of a subworkflow have completed,
but it has not yet called its output callback.  This can lead to the parent
workflow incorrectly believing no progress has been made and returning
'None' (which indicates a workflow deadlock if there are no jobs currently
executing) instead of re-evaluating pending steps to see if they can be run.
Additionally, this tweaks logging of start & completion to log start/stop pairing consistently (this creates a bit more logging but makes it clearer what is going on.)
> Move invocation of output callback for workflows 

- cwltool/draft2tool.py
Avoids using a Docker command line when `--no-container` passed.
This avoids creating an invalid Docker command line (with `None` as the
image). I believe this is a regression from here:
https://github.com/common-workflow-language/cwltool/commit/a91c16c343edf9ff7f52e3374ec1dfefe3d23799#diff-29ce315cc581b507c2832e379ce71ad6R175
cc @tetron
> No DockerCommandLineJob when use_container=False

- cwltool/main.py
Currently the only way to check whether the certain version of CWL file is supported by `cwltool` is to run `cwltool` with CWL files and to check its output.
This request adds `--print-supported-versions` that prints supported CWL versions.
We can check the CWL versions supported by `cwltool` by using this option.
Here is the output of `--print-supported-versions` option:
```console
$ ./cwltool.py --print-supported-versions
./cwltool.py 1.0.20170516234254
draft-2
draft-3
draft-3.dev1
draft-3.dev2
draft-3.dev3
draft-3.dev4
draft-3.dev5
draft-4.dev1
draft-4.dev2
draft-4.dev3
v1.0
v1.0.dev4
v1.1.0-dev1
```
> Add --print-supported-versions option that prints supported CWL versions

- Makefile
- cwltool/builder.py
- cwltool/cwlrdf.py
- cwltool/docker.py
- cwltool/docker_uid.py
- cwltool/draft2tool.py
- cwltool/expression.py
- cwltool/factory.py
- cwltool/flatten.py
- cwltool/job.py
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/mutation.py
- cwltool/pack.py
- cwltool/pathmapper.py
- cwltool/process.py
- cwltool/sandboxjs.py
- cwltool/stdfsaccess.py
- cwltool/update.py
- cwltool/workflow.py
- tests/test_check.py
- tests/test_examples.py
- tests/test_ext.py
- tests/test_fetch.py
- tests/test_js_sandbox.py
- tests/test_pack.py
- tests/test_toolargparse.py
- tests/util.py
Used https://github.com/timothycrosley/isort to sort package imports. Looks much cleaner now. :smiley:
> sorting python imports using isort

- .travis.yml
With this we can enable `build push` option and avoid double builds. Travis will build master branch on each merge. I tested this behavior on my local branch and output looks good. here https://travis-ci.org/kapilkd13/cwltool
> configuring build push for master branch only

- tests/wf/echo.cwl
When the system has installed the python 3 as the default interpreter some tests fail because of the workflow https://raw.githubusercontent.com/common-workflow-language/cwltool/1bdb36dbfce5f90dfd40878b00bb1a64261e15d7/tests/wf/echo.cwl assumes python 2 is used by default.
This happens when running `tox`, or when running `python setup.py install` under a python 2.7 virtual environment.
The test are very easy to fix: use python2 as the command, or making the code compatible with python 2 and 3. On the other hand changing the behaviour to open new processes under the same virtual environment might not.
For the time being I've fixed the tests under python 3.6 by adding a `__future__` import
> fix tests when python3 is installed as default

- tests/test_ext.py
In tes_ext file two different tests had same names therefore one was getting ignored. Renamed the second one. see line 60 and line 127 here https://github.com/common-workflow-language/cwltool/blob/master/tests/test_ext.py
> enabling a test that was ignored due to similar name

- cwltool/job.py
`file` is no longer a built-in with the new `io` framework. Was causing jobs to fail depending on the python in the conda env.
> Fix Python 3 incompatibility in PYTHON_RUN_SCRIPT.

- cwltool/schemas/README.md
- cwltool/schemas/doc/cli-description-languages-comparison.md
- cwltool/schemas/v1.0/CommandLineTool.yml
- cwltool/schemas/v1.0/Process.yml
- cwltool/schemas/v1.0/Workflow.yml
- cwltool/schemas/v1.0/conformance_test_v1.0.yaml
- cwltool/schemas/v1.0/v1.0/default_path.cwl
- cwltool/schemas/v1.0/v1.0/default_path_job.yml
- cwltool/schemas/v1.0/v1.0/inline-js.cwl
- cwltool/schemas/v1.1.0-dev1/Process.yml
- cwltool/schemas/v1.1.0-dev1/Workflow.yml
- cwltool/schemas/v1.1.0-dev1/conformance_test_v1.1.0-dev1.yaml
- cwltool/schemas/v1.1.0-dev1/v1.1.0-dev1/default_path.cwl
- cwltool/schemas/v1.1.0-dev1/v1.1.0-dev1/default_path_job.yml
> allow default files with bad path

- cwltool/builder.py
- cwltool/job.py
- cwltool/main.py
- cwltool/process.py
- tests/test_deps_env/random-lines/1.0/env.sh
With these changes I can get the requirement handling from #214 to work properly in simple toil tests (after a couple tweaks to toil itself). ~~I'll mark this as WIP until #214 is merged - though comments on the last few commits are more than welcome.~~
There are three commits here:
- aa1b7c996040026101e095526a06b088f88c0c36 - the main refactor which seems uniformly positive.
- 5069580853d6f2287a590a4d9b87d8793ebb0470 - which fixes a bug introduced at the last second in #214.
- 33d1e96b90054c94ba2d3f93fda9a6f6e4d2190a - contains a small tweak which might not be so great. It restores the ``builder`` parameter in ``single_job_executor`` on jobs before executing if it is supplied to the method. I'm guessing I'm somehow depending on ``builder`` later in the job lifecycle than the previous …
> Tweak SoftwareRequirement handling for reuse in Toil.

- cwltool/main.py
- cwltool/software_requirements.py
Previously the new options would always be suppressed in `cwltool --help`, now they will show up only if galaxy-lib is available.
I've also unified and improved the wording around the exceptions that get raised when these options are used but galaxy-lib is unavailable.
```
cwltool --beta-conda-dependencies tests/seqtk_seq.cwl tests/seqtk_seq_job.json
/Users/john/workspace/cwltool/.venv/bin/cwltool 1.0.20170708080313
Resolved 'tests/seqtk_seq.cwl' to 'file:///Users/john/workspace/cwltool/tests/seqtk_seq.cwl'
[job seqtk_seq.cwl] /private/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpr1IeGr$ seqtk \
seq \
-a \
/private/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmp9MWLCz/stg52d703ba-c684-46f0-ade9-2ae574004bea/2.fastq > /private/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpr1I …
```
> Polish help and error messages related to optional dependency on galaxy-lib.

- cwltool/main.py
Inspired by Dockstore's equivalent feature 
Will close https://github.com/common-workflow-language/cwltool/issues/384
> [wip] simple input object generation

- README.rst
- tox.ini
I just noticed the README on [PyPI](https://pypi.python.org/pypi/cwltool) is broken - this tweaks the README.rst formatting to fix that. We use the readme Python package to lint for this on Galaxy, Planemo, etc... and it prevents this breakage. I've added a tox rule for that here.
> README Linting and Fixes.

- cwltool/update.py
When cwltool tries to update a workflow that includes more than once the
same subworkflow an exception is raised. This is a product of the updating
procedure where workflows are passed by reference in the document. Once
a workflow has been updated, it should not be processed again -otherwise
expected keys will be missed.
This is a _hacky_ fix that **I do not expect to be merged** because it does not cover all use cases of the `update.py` script, but I thought it would be a good way to draft a possible solution. To test the problem, try running cwltool/cwl-runner with any DukeGCB top level pipelines with-control like [this one](https://github.com/Duke-GCB/GGR-cwl/blob/master/ChIP-seq_pipeline/pipeline-se-narrow-with-control.cwl). 
Try:
```
cwl-runner --debug …
```
> Avoid parse already parsed Workflows in update.py

- setup.py
the installation will not be blocked when running ``python setup.py install`` under Python 3 runtime.
> setup.py: remove condition which blocks python 3 install

- cwltool/stdfsaccess.py
Minor addition to https://github.com/common-workflow-language/cwltool/pull/464/commits/69d41788b917e8c95d88f1bd562c1443cc9e7eee
> cwltool/stdfsaccess.py: use io.open instead of builtin open

- appveyor.yml
- cwltool/main.py
- cwltool/pathmapper.py
Closes: https://github.com/common-workflow-language/cwltool/issues/483
> add size attribute to Files in the initial job object

- cwltool/sandboxjs.py
- decode subprocess.check_output calls to convert bytes to code
- rename term function to terminate for more clarity
- add some doc strings
Closes https://github.com/common-workflow-language/cwltool/issues/378
> sandboxjs.py: fix checking condition for node:slim

- cwltool/load_tool.py
- tests/test_cwl_version.py
- tests/wf/missing_cwlVersion.cwl
- tests/wf/wrong_cwlVersion.cwl
Fixes https://github.com/common-workflow-language/cwltool/issues/341, https://github.com/common-workflow-language/cwltool/issues/140
> load_tool: when no version or incorrect cwlVersion is found, create fatal error

- cwltool/builder.py
- cwltool/docker_id.py
- cwltool/job.py
Closes https://github.com/common-workflow-language/cwltool/issues/265
> feat: Pass group id (GID) in --user flag when calling docker run

- cwltool/load_tool.py
Addresses https://github.com/common-workflow-language/cwltool/commit/2c762b536caa0062aaf26d81df7745e246a6a1cf#commitcomment-23435763, https://github.com/common-workflow-language/cwltool/pull/491#issuecomment-318851330
cc: @jmchilton
> load_tool.py: Pass to regex before checking for acceptable versions

- jenkins.bash
Closes https://github.com/common-workflow-language/cwltool/issues/471
> jenkins.bash: Add support for Python 3 conformance testing

- requirements.txt
- setup.py
As suggested by Peter, we are moving to `2.12.4` as the min version for requests module
Closes: https://github.com/common-workflow-language/cwltool/issues/250
> changing requests min version to 2.12.4

- cwltool/builder.py
- cwltool/expression.py
- cwltool/main.py
- cwltool/process.py
- cwltool/sandboxjs.py
If this flag is present we strictly pull latest docker image even if the image is present locally
Closes #422
> adding --docker-pull flag to force pull image even if the docker image is already present

- cwltool/pathmapper.py
- cwltool/stdfsaccess.py
- tests/test_http_input.py
To allow remote http/https files as input.  Refer Issue #466
> [WIP] Allowing Http/Https files as input 

- cwltool/builder.py
- cwltool/draft2tool.py
- cwltool/job.py
Instead prefer to use basename or path.  Necessary to support engines such as
Toil with non-filename-preserving storage systems.
> Refactor secondaryFile handling to avoid basing on primary "location".

- cwltool/cwlrdf.py
- cwltool/main.py
- tests/test_rdfprint.py
Fixes ``--print-rdf`` flag under ``Python 3``. ``Python 2.7`` behaviour is unchanged
Before the changes, we got the following error: 
``` pytb
/home/manu/github/cwltool/venv3/bin/cwltool 1.0.20170801042110
I'm sorry, I couldn't load this CWL file.  The error was:
File "/home/manu/github/cwltool/cwltool/main.py", line 840, in main
printrdf(tool, document_loader.ctx, args.rdf_serializer, stdout)
File "/home/manu/github/cwltool/cwltool/cwlrdf.py", line 25, in printrdf
stdout.write(gather(wf, ctx).serialize(format=sr))
TypeError: write() argument must be str, not bytes
```
> cwltool/cwlrdf.py: Pass str rather than bytes to write function (Python 3 fix)

- appveyor.yml
- cwltool/builder.py
- cwltool/job.py
- cwltool/sandboxjs.py
Due to byte encoding of commands passed to `subprocess.Popen()`, a `TypeError: 'str' does not support the buffer interface` occured in python 3 on windows.
As per Docs:
>args should be a string, or a sequence of program arguments. The program to execute is normally the first item in the args sequence or the string if a string is given, but can be explicitly set by using the executable argument.
> Python 3 support on Windows

- cwltool/process.py
Should address https://github.com/common-workflow-language/common-workflow-language/pull/507
> Fix file literals when we aren't using Docker

- cwltool/draft2tool.py
- cwltool/main.py
- cwltool/mutation.py
setting generation field after schema validation and removing this generation field from the final output.
closes #382
> Removing unnecessary warning due to generation field

- cwltool/process.py
Relates to https://github.com/common-workflow-language/cwltool/issues/544
This PR adds:
* remove an existing directory before copying to avoid errors
* replace copy with copy2 for files when copying in order to preserve metadata. copytree uses copy2. This way all metadata is consistent for files and dirs.
> remove dir before copytree, use copy2 to keep metadata

- cwltool/draft2tool.py
- tests/test_examples.py
Fix #552. Could be merged now, but I am going to add a test for this
> Add a default None value for dockerimg variable

- cwltool/main.py
- cwltool/pack.py
* Create a subloader with an empty index.  Ensures that all cross
references (especially $imports) will be discovered and resolved for packing.
* Move pack to happen after tool loading (ensures everything has passed
validation before packing)
> Fixes to --pack behavior:

- cwltool/pack.py
- tests/test_pack.py
- tests/wf/formattest-job.json
- tests/wf/formattest.cwl
> Preserve namespaces after packing

- Makefile
- cwltool/draft2tool.py
- mypy.ini
- tox.ini
> sort globs according to POSIX

- cwltool/load_tool.py
- cwltool/main.py
- cwltool/workflow.py
- tests/test_pack.py
Cache the document loaders
Skip an unneeded deepcopy
Propogate the document metadata now that we aren't reparsing from disk
> reduce loading time for packed documents

- cwltool/workflow.py
Fix for https://github.com/common-workflow-language/cwltool/issues/592
> Fixing workflow default behavior

- README.rst
Hi, I noticed that the example given to use module thanks to the dependency resolver did not work. It was raising a `KeyError: 'module'` so I fixed that in the `dependency-resolvers-conf.yml`. Thanks !
> Fix typo in dependency-resolvers-conf.yml

- cwltool/main.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> Fixes typo in `--no-read-only` CLI help message.

- cwltool/process.py
Doesn't create unused temporary
directories when running Workflow
Closes: #636
> Closes #636, handles temp directory creation when running Workflow

- cwltool/argparser.py
- cwltool/factory.py
- cwltool/main.py
- tests/test_examples.py
and moving all command line parsing utilities from `main.py` to a new file `argparser.py`.
Closes #596
>  Add default command line arguments for cwltool as Factory 

- cwltool/job.py
- cwltool/main.py
Added options:
```
--record-container-id
If enabled, a file with suffix ".cid" will be created
storing the container ID under CIDFILE_DIR
--cidfile-dir CIDFILE_DIR
Directory for storing cidfiles. Default at /tmp/
--cidfile-prefix CIDFILE_PREFIX
Give a prefix to cidfile. Final file name will be
followed by a timestamp. Default empty.
--logtstp             Print timestamps with logging
```
> implement logging timestamps and record container ID in a file

- cwltool/argparser.py
Wrong default meant that schemas were _never_ being used, resulting in warnings.
Need a separate schema-salad fix to suppress warnings when skip_schemas is in effect.
> Fix --skip-schemas default.

- cwltool/argparser.py
- cwltool/draft2tool.py
- cwltool/process.py
- cwltool/workflow.py
While backticks are good for reStructuredText Docstring formatting
(PEP-0287) they aren't appropriate for printing to the user
> Single quote instead of backticks in output

- cwltool/workflow.py
I noticed that the `evl_timeout` cli parameter is not passed to `expression.do_eval` in `workflow.py`. This caused problems for me when running cwltool on a busy machine.
> Fix eval_timeout in workflow

- cwltool/argparser.py
- cwltool/main.py
closes #657 , closes #328, closes #258
> Set --tmp-outdir-prefix on MacOS to be under the shared volume by default

- cwltool/executors.py
- cwltool/process.py
- tests/test_examples.py
- tests/wf/cat-tool.cwl
> Fix --no-compute-checksum

- README.rst
This change adds 2 badges to the top of the readme, the appveyor one with status of windows builds, and the codecov with coverage info.
It also adds relevant text to the badges and removes the text that was next to them.
I would have changed the CWL conformance one to include the text inside the [badge](https://img.shields.io/jenkins/s/https/ci.commonwl.org/job/cwltool-conformance.svg?label=CWL%20conformance).
Unfortunately shields.io doesn't retrieve the info from Jenkins even though the [API endpoint](https://ci.commonwl.org/job/cwltool-conformance/api/json?tree=color) that should be queried works.
> Add Appveyor and codecov badges

- cwltool/load_tool.py
- tests/echo_broken_outputs.cwl
- tests/test_examples.py
Fixes #709
```
$ cwltool https://raw.githubusercontent.com/ska-sa/den/1c9e1f28bd06c07e808a82fd86f0cc25d08be251/main.cwl
/home/michael/cwltool/env3/bin/cwltool 1.0.20180403124038
Tool definition failed initialization:
Tool definition https://raw.githubusercontent.com/ska-sa/den/1c9e1f28bd06c07e808a82fd86f0cc25d08be251/steps/casa_applycal.cwl failed validation:
https://raw.githubusercontent.com/ska-sa/den/1c9e1f28bd06c07e808a82fd86f0cc25d08be251/steps/casa_applycal.cwl:158:1:   "outputs" section is not valid.
```
> better feedback on empty outputs section

- cwltool/software_requirements.py
Hi all,
The dependency resolver is only using the path of the config file specified by the user. If this path is relative and there is any change of working directory (for instance, `cwltoil` is changing its working directory), the dependency resolver will not be able to find the config file.
I propose a little fix to always transmit the absolute path of the config file to prevent this.
Cheers,
Kenzo
> Specify absolute path of config file for dependency resolver

- cwltool/process.py
instead of dumping the document tree. Fixes #712
> print line number for Avro exceptions when processing input section

- cwltool/load_tool.py
- cwltool/process.py
- tests/non_portable2.cwl
- tests/portable.cwl
- tests/test_examples.py
Do the check alongside other static checks.
Need to decide how best to fix the test that previously assumed this
was a validation error.
> Move var/spool/cwl detector to process.py and make it a warning.

- build-cwl-docker.sh
This request fixes docker image name for cwltool module.
Related:  #403
> Replace cwltool_module with cwltool-module

- .travis.yml
- cwltool/command_line_tool.py
- cwltool/process.py
- tests/test_examples.py
- tests/wf/cache_test_workflow.cwl
- tests/wf/touch_tool.cwl
This fixes the problem illustrated in #740. This also adds tests for this and changes `TestCache` to use a temporary directory instead of the folder `cache`.
> Fix #740 (cachedir not working in certain situations)

- Jenkinsfile
- Makefile
- appveyor.yml
- cwltool/docker.py
- cwltool/factory.py
- jenkins.bat
- tests/test_examples.py
- tests/test_fetch.py
- tests/test_iwdr.py
- tests/test_js_sandbox.py
- tests/test_parallel.py
- tests/test_toolargparse.py
- tests/util.py
- Runs tests on real Windows 7 system with Docker Toolkit (ci03.commonwl.org)
- Better error message if an input file/directory is on a path not mounted into the Docker VM
- Factory gains a parameter to customize the kwargs sent to load_tool/make_tool
- `make test` no longer collects coverage
- Test results are collected on Appveyor; not just overall pass/fail
> Better windows support

- cwltool/sandboxjs.py
There is no need to care what error has idiosyncratically been thrown, the only thing that matters is that the execution does not succeed.
Fixes #743
> Fix for issue #743, less stringent exception handling.

- requirements.txt
- setup.py
The code gates imports on os.name == "posix", so the dependency gates should match right? I'm guessing pip installing subprocess32 locally fixing problems means this was likely an issue - but let me know if this doesn't make sense.
> Include subprocess32 when building for Mac OS X.

- cwltool/argparser.py
- cwltool/command_line_tool.py
- cwltool/docker.py
- cwltool/extensions.yml
- cwltool/job.py
- cwltool/pathmapper.py
- cwltool/process.py
- cwltool/schemas/v1.1.0-dev1/CommandLineTool.yml
- cwltool/update.py
- cwltool/utils.py
- tests/test_ext.py
- tests/wf/networkaccess-fail.cwl
- tests/wf/networkaccess.cwl
- tests/wf/timelimit-fail.cwl
- tests/wf/timelimit.cwl
- tests/wf/workreuse-fail.cwl
- tests/wf/workreuse.cwl
> Support for v1.1 TimeLimit, WorkReuse and NetworkAccess

- cwltool/pathmapper.py
If present, include query part to generated basename in
normalizeFilesDirs.
> Handle situations where unique part of the url is in the query.

- README.rst
How to force factory `make` method to resolve `File` `path` as it's done in the reference `cwl-runner`?
I'm getting following exception:
```
WorkflowException: Invalid job input record:
Anonymous file object must have 'contents' and 'basename' fields.
```
> Fix typo in factory usage

- cwltool/provenance.py
This PR ensure that `metadata/` **is** included in the RO `metadata/manifest.json`, including then `metadata/provenance/primary.cwlprov.provn` and friends.  Note that  `metadata/manifest.json` itself is **not** included in its own aggregation, but should be (and is) included in the `tagmanifest*` files.
As well this PR fixes some relative paths in the generated manifest, they need `../` to access `workflow/` etc as the manifest file resides inside `metadata/`.
The `conformsTo` for cwlprov files is also set to CWLPROV_VERSION (aka https://w3id.org/cwl/prov/0.3.0) rather than the `__citation__` DOI.  
This may however add confusion as to if this profile specifies the RO structure or the structure of the PROV files, but the PROV files also say they conformTo their corresponding PROV spec, …
> Improve Research Object manifest

- cwltool/workflow.py
`cwltool` prints input and output object when `--debug` is specified for CommandLineTool.
For example:
```console
$ cwltool --debug echo.cwl
...
[job echo.cwl] initializing from file:///Users/tom-tan/echo.cwl
[job echo.cwl] {
"input": null
}
...
[job echo.cwl] completed success
[job echo.cwl] {
"output": {
"location": "file:///private/tmp/docker_tmpxrsdnrm2/output",
"basename": "output",
"nameroot": "output",
"nameext": "",
"class": "File",
"checksum": "sha1$834e8481813a87f4c25882bda3cd43808d6541aa",
"size": 365,
"http://commonwl.org/cwltool#generation": 0
}
}
...
{
"output": {
"location": "file:///Users/tom-tan/output",
"basename": "output",
"class": "File",
"checksum": "sha1$834e8481813a87f4c25882bda3cd43808d6541aa",
"size": 365,
"path": "/Users/tom-tan/output"
}
}
Final process status …
```
> Print input and output objects for workflow when debugging

- cwltool.py
- cwltool/__main__.py
- cwltool/job.py
- cwltool/main.py
- cwltool/sandboxjs.py
- cwltool/utils.py
- requirements.txt
- setup.py
(This is a bit of an ugly solution, but I can't see a better way to do it.)
As processes are spawned, they are added to a global list of processes (`utils.processes_to_kill`); when the program exits (either due to execution finishing, an exception being raised, or SIGTERM), `_terminate_processes` is called, and kills all the processes in that list. A new entrypoint `run` is added to do the necessary try/finally to make this happen.
Caveats:
- since Python doesn't allow to kill individual threads, those threads can continue to execute while we're pulling the rug from under their feet, potentially leading to unexpected behaviour
- there's always the chance that a thread could spawn a process after we've killed all the processes, but before Python exits (though this should be very rare) …
> Kill child processes when cwltool exits

- cwltool/docker.py
This request fixes a typo in an error message in the following case.
```console
$ cwltool --debug --leave-container --timestamps --compute-checksum --record-container-id --cidfile-dir $PWD/out --outdir $PWD/out ~/common-workflow-language/v1.0/v1.0/search.cwl ~/common-workflow-language/v1.0/v1.0/search-job.json
[2018-08-29 14:21:26] /Users/tom-tan/.pyenv/versions/3.6.5/bin/cwltool 1.0.20180820141117
...
[2018-08-29 14:21:28] --cidfile-dir /Users/tom-tan/out error:
/Users/tom-tan/out%s is not a directory or directory doesn't exist, please check it first
```
In the last line, the error message accidentally contains `%s`.
```console
$ cwltool --debug --leave-container --timestamps --compute-checksum --record-container-id --cidfile-dir $PWD/out --outdir $PWD/out …
```
> Fix typo in error message

- .gitignore
- cwltool/process.py
- cwltool/utils.py
- requirements.txt
- setup.py
- tests/test_ext.py
- tests/wf/updateval.cwl
- tests/wf/updateval_inplace.cwl
for all the files in the destination directory
> Make data relocation at the end of workflow  runs faster

- cwltool/executors.py
- cwltool/process.py
Fixes #892.
The current behaviour goes back to at least cwltool version
1.0.20170723124118.
> Delete intermediate outputs even when they exist

- README.rst
- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/executors.py
- cwltool/job.py
- cwltool/main.py
- cwltool/process.py
- cwltool/provenance.py
- cwltool/workflow.py
- tests/test_provenance.py
Remove make_fs_access from ProvenanceProfile
Decouple adding start and stop times to profiles from the actual time it
happens
Decouple adding prospective provenance from the start of a process
This is preparatory work for https://github.com/DataBiosphere/toil/issues/2390
> maintenance: refactor code in provenance

- setup.py
- tests/test_dependencies.py
- tests/test_deps_env/modulefiles/random-lines/1.0
- tests/test_deps_env_modules_resolvers_conf.yml
This PR adds a test for resolving software requirements using [Environment Modules](http://modules.sourceforge.net). This is a basic service of **galaxy-lib**, but only works since galaxyproject/galaxy@69a87003f70e3925554fcc88fd2080edab619ed1, available in 17.09.9 dated 2017-09-21. The test demonstrates that version 17.09.3 of galaxy-lib is inadequate. See #983
Specifically this PR:
* Adds a test using type `modules` for dependency resolvers configuration
* Specifies that the resolver use the find by directory strategy
* Adds a modulefile for random-lines in tests/test_deps_env/
* Bumps galaxy-lib to minimum **17.09.9**
The test is skipped if the command `modulecmd` is not available. To test this PR in CI one must add environment modules to the configuration of the build node.
> Resolve software requirements using Environment Modules

- cwltool/singularity.py
- cwltool/utils.py
- requirements.txt
- setup.py
This patch allows dropping the subprocess32 dependency for python>=3.5.
I do not have py3.2-3.5 here, so I haven't tested on those.
> use subprocess from stdlib on python>=3.5

- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/pathmapper.py
- cwltool/workflow.py
We decided to limit these and cause a hard error if these buffer sizes were exceeded. We decided this would retro-actively apply to v1.0 - since silently failing (the unspecified but actual behavior of cwltool) seems to be the worst of all behaviors.
Corresponding PR to conformance tests at https://github.com/common-workflow-language/common-workflow-language/pull/822.
> Limit loadContents/File literal contents length.

- cwltool/process.py
For https://github.com/common-workflow-language/cwltool/issues/1038
> use 1024MiB as the default memory size in v1.0, else use 256MiB

- MANIFEST.in
- README.rst
- cwltool/resolver.py
- tests/test_trs.py
- tests/trs/Dockstore.cwl
- tests/trs/md5sum-tool.cwl
- tests/trs/md5sum-workflow.cwl
* resolve imports properly for TRS
test with commands like the following for command-line tools (previously working)
```
$ cat test.json
{
"input_file": {
"class": "File",
"path": "md5sum.input"
}
}
(venv) $ cwltool --make-template quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4 test.json
/home/dyuen/cwltool/venv/bin/cwltool 1.0.20190323055837
Resolved 'quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4' to 'https://dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fbriandoconnor%2Fdockstore-tool-md5sum/versions/1.0.4/plain-CWL/descriptor/Dockstore.cwl'
input_file:  # type "File"
class: File
path: a/file/path
(venv) $ cwltool quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4 test.json
/home/dyuen/cwltool/venv/bin/cwltool 1.0.20190323055837
Resolved …
```
> WIP Fix resolver for imports

- cwltool/context.py
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/process.py
- cwltool/update.py
- tests/test_load_tool.py
Sanity check tool has been updated to expected internal version before
executing.
> Make do_update optional to override updating behavior.

- cwltool/command_line_tool.py
- cwltool/load_tool.py
- cwltool/update.py
- tests/test_load_tool.py
This flag is used internally by schema salad to determine when it is
appropriate to run checklinks, but checklinks must not be skipped
entirely as it includes updating fields in certain circumstances.
> "checklinks" flag should not be based on do_validate

- README.rst
Just followed a link from the user guide - this should mention the Debian package that cwltool provides via the official Debian channels. I tend to think that the way this was formulated is very vendor-neutral.
> Introduced reference to Debian+Conda

- cwltool/load_tool.py
- tests/test_pack.py
From resolve_and_validate return uri with the added id fragment and
use it downstream to reference the document.
> If document has an id: field, use it.

- cwltool/load_tool.py
- cwltool/main.py
Eliminate spurious warning when input document has a format identifier with a prefix only defined in the tool document.  Also fixes behavior of applying resolution to other fields called "format" that are not actually supposed to be file formats.
> Don't resolve format fields on initial load of job order object.

- cwltool/job.py
- Fix CWL's memory usage calculation
- Change getting system memory from Docker's HostConfig.Memory to `psutil's virtual_memory()`
Fixes https://github.com/common-workflow-language/cwltool/issues/1109
> CWL memory usage report

- cwltool/pack.py
- cwltool/process.py
1) allows result from pack() to be re-run back through resolve_all
2) scandeps no longer adds dependencies for same-file cross references.
> Tweak packing and scandeps

- cwltool/job.py
- tests/test_udocker.py
Fixes #1182 by reducing to the real underlying error, Docker wasn't able to mount the path due to Windows system permission problems
> handle error in cidfile removal more gracefully

- jenkins.bash
This PR pushes the conformance badges generated in the Jenkins server to [common-workflow-language/conformance](https://github.com/common-workflow-language/conformance) repository.
These conformance badges are useful for users to check how a given engine satisfies CWL specification.
> Push conformance badges to commonwl/conformance repository

- jenkins.bash
It just copy `cwltool_$version` to `cwltool_latest` generated in Jenkins CI because symlink does not work in Github.
It is not the best solution but it is enough as a workaround.
> Provide cwltool_latest for badges

- appveyor.yml
> test with Python 3.8 on appveyor

- README.rst
It contains two changes to the conformance badges:
- Use non-flat badges as same as the other type of badges
- Before: ![before](https://flat.badgen.net/https/raw.githubusercontent.com/common-workflow-language/conformance/master/cwltool/cwl_v1.0/cwltool_latest/command_line_tool.json)
- After: ![after](https://badgen.net/https/raw.githubusercontent.com/common-workflow-language/conformance/master/cwltool/cwl_v1.0/cwltool_latest/command_line_tool.json)
- Add the commonwl icon to the conformance badges
- Before: ![before](https://badgen.net/https/raw.githubusercontent.com/common-workflow-language/conformance/master/cwltool/cwl_v1.0/cwltool_latest/command_line_tool.json)
- After: ![after](https://badgen.net/https/raw.githubusercontent.com/common-workflow-language/conformance/master/cwltool/cwl_ …
> Use non-flat badges with the commonwl icon for conformance badges

- cwltool/argparser.py
- tests/test_toolargparse.py
- tests/with_doc.cwl
- tests/without_doc.cwl
It would be nice if `--help` also shows the `doc` field in a given CWL doccument.
Example input(example.cwl):
```cwl
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
message:
doc: message to be printed
type: string
inputBinding:
position: 1
outputs: []
doc: Useful message for this tool
```
Before this PR:
```console
$ cwltool example.cwl --help
...
usage: example.cwl [-h] --message MESSAGE [job_order]
positional arguments:
job_order          Job input json file
optional arguments:
-h, --help         show this help message and exit
--message MESSAGE  message to be printed
```
After merging this PR:
```console
$ cwltool example.cwl --help
...
usage: example.cwl [-h] --message MESSAGE [job_order]
Useful message for this tool     # <---- Added! …
```
> Add `doc` field message to the output of `--help`

- .gitignore
- cwltool/docker.py
- tests/test_docker.py
- tests/test_docker_paths_with_colons.py
This will fix #1250. Paths with colons can not be specified with the `--volume` syntax. They can, using `--mount`... and the parameter can also use CSV quoting in case there is a comma in a path.
- Would you like a test that actually runs docker, with a mounted path with weird characters?
- `--volume` will create the directory if it does not exist. `--mount` will not. [docker docs](https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior). I could add an `os.mkdir()` to handle this?
> Change from --volume to --mount

- cwltool/load_tool.py
- cwltool/main.py
- cwltool/pack.py
- setup.py
- tests/test_pack.py
- tests/test_procgenerator.py
- tests/wf/scatter2.cwl
- tests/wf/scatter2_subwf.cwl
Bump version to 3.0 because pack() API was changed in non-backwards
compatible way.
> Add test for packing a fragment of a document & fix.

- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/process.py
Apropos my PR on the schema_salad repo (https://github.com/common-workflow-language/schema_salad/pull/324) make cwltool supply `Optional[str]` args as `None` when they are absent instead of `""`.
This change does NOT require a version bump of schema_salad in requirements.txt
> Use schema_salad.avro.schema.Name according to docs

- cwltool/command_line_tool.py
This is a super simple fix to the issue on Windows 10 for collecting secondary files on outputs I described here: https://cwl.discourse.group/t/secondary-files-cannot-be-collected-by-cwltool-on-windows-10/158
> change hardcoded path sep to os.sep

- cwltool/process.py
- tests/scatter_numbers.cwl
- tests/test_examples.py
When a scatter step in a workflow is chosen as a step in an output, the output names will naturally clash. Here is an example workflow:
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.1
class: Workflow
inputs:
range:
type: int
outputs:
output:
type: File[]
outputSource:
generate_files/output
steps:
generate_list:
requirements:
- class: InlineJavascriptRequirement
run:
class: ExpressionTool
inputs:
max: 
type: int
default: 100
outputs:
numbers:
type: int[]
expression: |
${
var numberList = Array.apply(null, Array(inputs.max)).map(function(_, i) { return i});
return { "numbers": numberList } 
}
in:
max: range
out:
- numbers
generate_files:
requirements:
- class: ScatterFeatureRequirement
scatter: number
run:
class: CommandLineTool
inputs:
number:
type: int
inputBinding:
position: 10 …
```
> Fix algorithm for generating output names when output names clash

- cwltool/job.py
This fixes a minor bug where, on timeout of a job, the message returned contains the text "willbe terminated".
> Fix typo in timeout message

- cwltool/load_tool.py
- tests/test_recursive_validation.py
Like `resolve_and_validate_document`, but it also calls `make_tool`, bringing in additional validation.
Discussed in https://github.com/galaxyproject/gxformat2/issues/51.
> Added recursive_resolve_and_validate_document

- cwltool/job.py
- cwltool/process.py
This was causing some errors attempting to resolve paths for `toilfs:{path}` paths in Toil, and this PR should resolve the issue.  Also fixes a spelling error.
> Add fs_access for unknown URIs in relocateOutputs() _realpath().

- Makefile
- build-cwl-docker.sh
- cwltool-in-docker.sh
- release-test.sh
- tox.ini
- travis.bash
This request makes `cwltool-in-docker.sh` to check the existence of the `DOCKER_HOST` environment variable in addition to the existence of `/var/run/docker.sock`.
This script is used in the [cwltool container image](https://hub.docker.com/r/commonworkflowlanguage/cwltool).
In the current implementation, it checks `/var/run/docker.sock` and aborts if it does not exist.
However, it is too restrictive because using `DOCKER_HOST` can achieve the same objective.
This request removes this restriction.
> Fix cwltool-in-docker.sh to accept DOCKER_HOST

- cwltool/command_line_tool.py
- cwltool/job.py
- cwltool/process.py
* Fix long standing bug creating useless empty temp directories, cluttering up user's filesystem
* Fix correctness issue getting `loadListing` from `outputBinding`.
> No useless dirs

- requirements.txt
Hi Michael-
Apropos enabling CI on Github Actions, I've looked over the requirements.txt etc.
(See also #1408)
I spotted that pydot was missing from requirements.txt, but unlike argcomplete, there is a clear version specifier in setup.py for this so I have added it.
Cheers
> add pydot to requirements.txt, version as in setup.py

- .github/workflows/ci-tests.yml
Hopefully resolve why this passes:
https://github.com/common-workflow-language/cwltool/runs/2058705861?check_suite_focus=true
and this fails:
https://github.com/common-workflow-language/cwltool/runs/2058861887?check_suite_focus=true
> CI: only create a local branch for PRs

- .github/workflows/ci-tests.yml
It would be handy to be able to trigger workflows manually, e.g. if you have a branch that's not ready for a PR. To enable this, GH requires that the default branch of your repo have a workflow with `workflow_dispatch` among its triggers.
> allow manual workflow triggering

- cwltool/singularity.py
Due a very long story (running `cwltool --singularity` on a FUSE mounted filesystem) I realized the detection of user namespaces feature on available singularity binary was broken. This pull request is a one-line addition which fixes it for at least singularity 3.5 and 3.7 .
> Fixed singularity user namespace feature detection

- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/main.py
In the course of updating the deps/env stuff, I noticed a test failing that I could not reproduce locally
https://github.com/rupertnash/cwltool/runs/2125145168?check_suite_focus=true#step:9:142
I figured out this was because the global variable `cwltool.command_line_tool.ACCEPTLIST_RE` gets set based on the command line args and this state leaks when running tests in-process (sorry)
In this commit I propose a fix
> remove relaxed/strict path checking global state

- setup.py
- tox.ini
My bug fix here
https://github.com/common-workflow-language/cwltool/pull/1424
broke galaxy, which I fixed here
https://github.com/galaxyproject/galaxy/pull/11655
This PR updates tox config to install an appropriate version of `galaxy-tool-util`
> set minimum version of galaxy-tool-util that copes with relaxed path

- MANIFEST.in
- cwltool/pack.py
- tests/test_pack.py
- tests/wf/operation/abstract-cosifer.cwl
- tests/wf/operation/expect_operation-single_packed.cwl
- tests/wf/operation/operation-single.cwl
CWL 1.2 introduced [Operation](https://www.commonwl.org/v1.2/Workflow.html#Operation) in order to model abstract workflow steps, needed to use CWL to describe a workflow which could not exist or be implemented in a different way than CWL.
As `cwltool --pack` was ignoring records of class `Operation`, packed workflows were not correct (they did not validate with `cwltool --validate`). The issue was explained at https://github.com/common-workflow-language/cwltool/issues/1466.
These commit and test fix the issue which arises while packing workflows having `Operation` records, and its work.
> Allow packing Operation records

- .snyk
- requirements.txt
- setup.py
The dependency chain is
cwltool -> prov -> networkx -> numpy
> Pin networkx so we don't install numpy, scipy and pandas by default.

- cwltool/process.py
- tests/test_schemadef.py
- tests/wf/schemadef-bug-1473.cwl
> Validates file with SchemaDefRequirement

- cwltool/context.py
- cwltool/job.py
- tests/test_streaming.py
> Allow files to be named pipes

- cwltool/process.py
- tests/symlinks.cwl
- tests/test_relocate.py
> better handle symlinks in Directories

- cwltool/process.py
- cwltool/utils.py
- tests/test_iwdr.py
- tests/wf/iwdr_permutations_nocontainer.cwl
Fix for #1480 
* add include_root option to set root dir writable in ensure_writable
* set include_root=True when making workdir writable
> bug/1480: make writable workdir actually writable

- cwltool/pack.py
- tests/test_pack.py
- tests/wf/expect_packed.cwl
- tests/wf/expect_revsort_datetime_packed.cwl
- tests/wf/expect_trick_packed.cwl
- tests/wf/scatter2_subwf.cwl
As per schema-salad, `$namespaces` are only valid in the root document:
https://www.commonwl.org/v1.0/SchemaSalad.html#Explicit_context
https://www.commonwl.org/v1.1/SchemaSalad.html#Explicit_context (same as v1.0)
https://www.commonwl.org/v1.2/SchemaSalad.html#Explicit_context (same as v1.0, v1.1)
Inspired by (and partial fix for) https://github.com/common-workflow-language/cwl-utils/issues/71#issuecomment-912887777
> pack: add $namespaces to the (effective) root only

- cwltool/command_line_tool.py
A more detailed error message for "paths starting with '/' only permitted in CWL 1.2 and later".
Fixes #1356
> CWL v1.[01] listing with an absolute path: a more helpful error message 

- cwltool/builder.py
This is needed for toil-cwl-runner (and others) as some secondaryFile
expressions can modify other entries in a way that would cause
them to not pass validatation a second time
Example conformance test:
command_input_file_expression: Confirm CommandInputParameter expression can receive a File object
> trust given secondaryFiles if !discover_secondaryFiles

- cwltool/command_line_tool.py
- tests/test_path_checks.py
Fixes #1445; command_line_tool.collect_output() now URL decodes output file `basename`s, and uses the decoded result to determine the `nameroot` and `nameext` fields
> Fix erroneous URL encoding of final output filenames

- cwltool/executors.py
- tests/test_tmpdir.py
For issue reported on Discourse: https://cwl.discourse.group/t/cwl-runner-tmpdir-not-deleted/401
When debugging the example from https://www.commonwl.org/user_guide/02-1st-example/index.html, with the command line `cwltool --tmpdir-prefix /tmp/cwl/ /tmp/1st-tool.cwl /tmp/echo-job.yml`, I noticed the `output_dirs` being set to an empty list.
The issue was because the `runtime_context.cachedir` was not `None`, but it was an empty string. So the value of `output_dirs` was incorrectly initialized.
Pending a unit/functional test as I have to learn how to write those for `cwltool` :grimacing: any pointers?
Thanks
> Remove temporary directories when cache dir is empty string

- cwltool/job.py
> Add helpful error message when a program is terminated by a (Unix) signal, such as a segfault

- cwltool/context.py
- cwltool/process.py
- tests/test_examples.py
> add better string representation for Process objects

- cwltool/main.py
Fix for the `cwltool` side of https://github.com/DataBiosphere/toil/issues/3965
> _terminate_processes for non-docker processes, like nodejs

- cwltool/main.py
- cwltool/singularity.py
- tests/test_cuda.py
- tests/test_make_template.py
- tests/test_relocate.py
If Ruamel encounters a blank comment string "" instead of None it throws a hissy fit. This happened for me when an input was of type 'Record' using `--make-template`
```
read_names:
type:
- type: record
```
```
File "~/dev/capanno-utils/lib/python3.6/site-packages/cwltool/main.py", line 972, in main
make_template(tool)
File "~/dev/capanno-utils/lib/python3.6/site-packages/cwltool/main.py", line 732, in make_template
generate_input_template(tool),
File "~/dev/capanno-utils/lib/python3.6/site-packages/cwltool/main.py", line 299, in generate_input_template
template.insert(0, name, value, comment)
File "~/dev/capanno-utils/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 722, in insert
self.yaml_add_eol_comment(comment, key=key)
File …
```
> Protect ruamel from blank comment strings when making templates

- cwltool/workflow.py
- tests/subgraph/steplevel-resreq.cwl
- tests/test_subgraph.py
> single-process: handle step-level req collisions

- cwltool/subgraph.py
- tests/subgraph/env-wf2_long.cwl
- tests/subgraph/env-wf2_subwf_b.cwl
- tests/test_subgraph.py
when use --single-step step2_tool parameter to run step in workflow meet this error
```
File "/d/project/cwltool-main/cwltool/main.py", line 1181, in main
ctool = choose_step(args, tool, loadingContext)
File "/d/project/cwltool-main/cwltool/main.py", line 861, in choose_step
extracted = get_step(tool, step_id, loading_context)
File "/d/project/cwltool-main/cwltool/subgraph.py", line 225, in get_step
name = outport.split("#")[-1].split("/")[-1]
AttributeError: 'CommentedMap' object has no attribute 'split'
```
> fix --single-step step2_tool error

- cwltool/errors.py
- cwltool/load_tool.py
- cwltool/main.py
- tests/test_misc_cli.py
- tests/test_validate.py
- tests/wf/packed_no_main.cwl
Should this be a new command line option `--validate-all`? That would make sense if users were using `--validate` to determine "is this URL a valid reference to a CWL Process" despite the option's help text being "Validate CWL document only"
> --validate works with $graph docs lacking a "main"

- cwltool/main.py
- cwltool/subgraph.py
- tests/subgraph/count-lines17-wf.cwl.json
- tests/test_subgraph.py
--print-targets now correctly prefixes sub-workflow steps
Fixes #1604
> Single-step: inline and deeply nested sub-workflows

- cwltool/builder.py
- tests/test_examples.py
- tests/wf/bad_formattest2.cwl
```
WARNING  salad:load_tool.py:381 URI prefix '${ return ["http' of '${ return ["http://edamontology.org/format_2330", 42];}
' not recognized, are you missing a $namespaces section?
WARNING  salad:load_tool.py:381 URI prefix '${ return ["http' of '${ return ["http://edamontology.org/format_2330", 42];}
' not recognized, are you missing a $namespaces section?
WARNING  salad:load_tool.py:381 URI prefix '${return "http' of '${return "http://edamontology.org/format_2330";}
' not recognized, are you missing a $namespaces section?
WARNING  salad:load_tool.py:381 URI prefix '${return "http' of '${return "http://edamontology.org/format_2330";}
' not recognized, are you missing a $namespaces section?
```
> more expr parsing tests

- cwltool/argparser.py
- cwltool/executors.py
- cwltool/job.py
- cwltool/main.py
- tests/test_toolargparse.py
Uses loader's urljoin to construct relative references based on the file uri of the current working directory, which allows other types of URIs to pass through the command line unbothered.
Also handle edge case where input parameter type is wrapped in single-item list.
> Handle URLs for command line inputs

- cwltool/main.py
- cwltool/process.py
- tests/test_examples.py
- tests/wf/dir_deps.json
When getting back a list of dependencies, and using "nestdirs", in the
specific case it there are references to both a directory and files
within that directory, it may report multiple dependencies for the
same directory.  The mergedir method merges those references into one.
> scandeps should not apply mergedirs at every level

- cwltool/__init__.py
When I run the workflow uploaded on [Zenodo](https://zenodo.org), I get the following warning because Zenodo responds it as Content-Type `application/octet-stream`.
```
While fetching https://sandbox.zenodo.org/record/1016630/files/trimming_and_qc.cwl, got content-type of 'application/octet-stream, application/octet-stream'. Expected one of ['text/plain', 'application/json', 'text/vnd.yaml', 'text/yaml', 'text/x-yaml', 'application/x-yaml'].
```
curl results:
```bash
$ curl -I https://sandbox.zenodo.org/record/1016630/files/trimming_and_qc.cwl
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/octet-stream
Content-Length: 1151
Content-MD5: 415878c78ed8265bd7367099cf2254f7
Content-Security-Policy: default-src 'none';
X-Content-Type-Options: nosniff
X-Download-Options: noopen …
```
> Add application/octet-stream

- cwltool/argparser.py
- cwltool/main.py
- tests/test_examples.py
- tests/wf/paramref_arguments_roundtrip.cwl
Fixes #780 
-  [ ] propose `tests/wf/paramref_arguments_roundtrip.cwl` as a conformance test for CWL v1.2.1
> Allow records with defaults to be accepted, also type longs

- cwltool/argparser.py
The continued strings on a separate line just get ignored by the runtime. You need to put them in parentheses to turn them into a single string.
> Fix a few help texts

- cwltool/cuda.py
- cwltool/docker.py
- cwltool/executors.py
- cwltool/extensions-v1.1.yml
- cwltool/extensions.yml
- cwltool/job.py
- cwltool/process.py
- cwltool/singularity.py
- mypy-requirements.txt
- tests/test_cuda.py
- tests/wf/nvidia-smi-cc.cwl
- tests/wf/nvidia-smi-container.cwl
- tests/wf/nvidia-smi-max.cwl
- tests/wf/nvidia-smi-range.cwl
- tests/wf/nvidia-smi.cwl
* Revise CUDARequirement so to support expressions to choose how many GPUs we want.
* adjust cudaComputeCapability to take an array of explicit versions to use
> Cuda request gpu device expr

- docs/index.rst
- docs/pythonversions.rst
Added "Python version support policy" page to documentation.
> cwltool Python support policy

- cwltool/cwlrdf.py
- mypy-requirements.txt
- tests/test_examples.py
Removed primary file path prefix from graph labels
> print-dot: Removed primary path prefix from graph labels

- .github/workflows/ci-tests.yml
- cwltool/cwlviewer.py
- cwltool/rdfqueries/get_inner_edges.sparql
- tests/test_examples.py
- tests/wf/three_step_color.cwl
Node color/style:
- CommandLineTool: "lightgoldenrodyellow", "filled"
- Workflow: "#F3CEA1", "filled"
- Operation: [no color], "dashed"
CommandLineTool & Workflow now have the same color as [cwlviewer](https://github.com/common-workflow-language/cwlviewer).
> Changed cwlviewer.py to make node color dependent on operation class

- cwltool/singularity.py
- tests/test_environment.py
- tests/test_singularity_versions.py
This is a fix for problems related to #1572 .
I refactored get_version and its cache to return not only the version number, but include the singularity "flavor" (distribution). This currently can be "apptainer", "singularity-ce", or "singularity" as far as I know. I also refactored the function to return version numbers directly as a tuple of integers to simplify subsequent checks. The get_version function currently seems to be used only from within the singularity.py module and is used by various is_singularity_X_Y_or_newer functions.
I added a new function for checking for apptainer 1.0 or higher. Apptainer 1.0 is (currently) equivalent to singularityCE 3.9.5 (see https://github.com/apptainer/apptainer/releases). Therefore I also adapted the other version checking functions to return …
> Enhanced detection of singularity version including a distribution detection

- README.rst
Found the broken link when I was going to test https://github.com/common-workflow-language/cwltool/issues/782 :+1:
> Fix udocker installation link

- cwltool/executors.py
Was having a discussion about how some people have trouble distinguishing between the capabilities of `cwltool` and the broader CWL ecosystem.  It occurred to me that we could just tell people, clearly, to look elsewhere (and where to look).
Also added a message about the existence of the `--parallel` option.
```
INFO /home/peter/work/cwltool/venv3/bin/cwltool 3.1.20220519125739
INFO Resolved 'revsort.cwl' to 'file:///home/peter/work/cwl-v1.2/tests/revsort.cwl'
INFO Using default serial job executor.  Use `cwltool --parallel` to run multiple steps at a time.
INFO [workflow ] start
INFO [workflow ] starting step rev
...
INFO [job sorted] Max memory used: 0MiB
INFO [job sorted] completed success
INFO [step sorted] completed success
INFO [workflow ] completed success
INFO Need to grow beyond …
```
> Message about using --parallel, and how other CWL runners are available.

- cwltool/argparser.py
- cwltool/context.py
- cwltool/process.py
- cwltool/sandboxjs.py
- cwltool/validate_js.py
- tests/test_singularity_versions.py
This PR is in response to [issue 1680](https://github.com/common-workflow-language/cwltool/issues/1680).
1. Increased the default time for expression tools to 60 seconds, so that `--eval-timeout` flag will be used more for optimisation purposes, rather than being needed to accomodate systems with slower response times for expression tools.
2. Added some log information for situations where the expression tool time limit is triggered.
Outstanding questions:
1. The `exec_js_process` routine seems to be used for organisational tasks at the start of the workflow. And is run with a 30 second time limit. If the tool time limit gets breached for that process then my log message will be misleading (because the `--eval-timeout` flag doesn't control that time limit).
2. Really it would be useful …
> Expressiontool timer

- cwltool/job.py
- cwltool/main.py
`logging.warn` is deprecated since Py 3.3. Noticed the warnings (about logging.warn) in GH Actions logs for another PR.
To review, we can wait CI and just look at a `pytest` and/or `mypy` test to confirm there's no warning about warn.
-Bruno
> logging.warn is deprecated, use warning

- Makefile
- cwltool/pathmapper.py
- cwltool/utils.py
- setup.py
- test-requirements.txt
- tests/test_http_input.py
Changed cwltool/utils.py::downloadHttpFile to set Last-Modified date of remote file as timestamp of downloaded file.
> Set last modification date of remote file as local file timestamp

- CODE_OF_CONDUCT.md
- Makefile
- cwltool/run_job.py
- setup.cfg
I think `codespell` is failing in other PR's:
- https://github.com/common-workflow-language/cwltool/pull/1703
- https://github.com/common-workflow-language/cwltool/pull/1714
- https://github.com/common-workflow-language/cwltool/pull/1709
I tested it locally, and it reformatted a few files. I excluded the word ORE as that's from an ontology's name. After the changes in this PR, `make cleanup` passes with exit code `0` for me :tada: 
```bash
(venv) kinow@ranma:~/Development/python/workspace/cwltool$ make cleanup
isort cwltool/argparser.py cwltool/builder.py cwltool/checker.py cwltool/command_line_tool.py cwltool/context.py cwltool/cuda.py cwltool/cwlrdf.py cwltool/cwlviewer.py cwltool/docker_id.py cwltool/docker.py cwltool/env_to_stdout.py cwltool/errors.py cwltool/executors.py …
```
> Fix codespell issues

- cwltool/singularity.py
- tests/debian_image_id2.cwl
- tests/echo-job.yaml
- tests/non_portable.cwl
- tests/non_portable2.cwl
- tests/portable.cwl
- tests/sing_pullfolder_test.cwl
- tests/test_docker_info.py
- tests/test_singularity.py
- tests/test_tmpdir.py
- tests/test_udocker.py
- tests/wf/1590.cwl
- tests/wf/cat-tool.cwl
- tests/wf/directory.cwl
- tests/wf/expect_packed.cwl
- tests/wf/expect_revsort_datetime_packed.cwl
- tests/wf/expect_trick_packed.cwl
- tests/wf/iwdr_permutations.cwl
- tests/wf/literalfile.cwl
- tests/wf/networkaccess-fail.cwl
- tests/wf/networkaccess.cwl
- tests/wf/revsort.cwl
- tests/wf/revsort_datetime.cwl
- tests/wf/secret_wf.cwl
- tests/wf/touch_tool.cwl
- tests/wf/trick_revsort.cwl
- tests/wf/updateval.cwl
- tests/wf/updateval_inplace.cwl
- tests/wf/workreuse-fail.cwl
- tests/wf/workreuse.cwl
As inspired by the list at
https://github.com/common-workflow-language/cwl-v1.2/blob/1.2.1_proposed/CONFORMANCE_TESTS.md#writing-a-new-conformance-test
Also fixes a Singularity 3 bug
> tests: reduce number of software containers

- cwltool/builder.py
- mypy-requirements.txt
- requirements.txt
- setup.py
As a consequence of this cwl-utils [PR](https://github.com/common-workflow-language/cwl-utils/pull/141).
> Import check_format from cwl-utils

- CONTRIBUTING.md
I tried the "traditional workflow" described in CONTRIBUTING.md but got the following error:
```
ERROR: Double requirement given: ruamel.yaml<0.17.22,>=0.16.0 (from -r mypy-requirements.txt (line 2)) (already in ruamel.yaml<0.17.22,>=0.15 (from -r requirements.txt (line 3)), name='ruamel.yaml')
```
That was with pip 20.0.2. I solved by updating pip to the latest version, hence this PR.
> CONTRIBUTING.md: recommend updating pip in the dev venv

- cwltool/provenance.py
- tests/test_provenance.py
When the workflow has no input or output files, the RO created by `cwltool --provenance` has no files under `data/`. In this case, no bagit manifest is created, making the RO bag invalid:
```python
from bdbag.bdbagit import BDBag
bag = BDBag("ro")
bag.validate()
```
```
bagit.BagValidationError: No manifest files found
```
This PR changes `ResearchObject` so that it creates an empty manifest to fix the bagit structure in such cases.
> Provenance: fix bagit structure when there are no data files

- cwltool/command_line_tool.py
Conformance tests here:
https://github.com/common-workflow-language/cwl-v1.2/pull/199
> Handle relative paths and locations in cwl.output.json

- .github/workflows/quay-publish.yml
It seems that there is no Docker image for Arm, so I added options to the publish action.
Please refer https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
I would be happy to discuss, including whether or not to provide Arm image itself.
> Add QEMU step and platforms field to the publish action for Arm Docker image

- cwltool/process.py
- cwltool/utils.py
> allow mypy process type to be used as by interpreted subclasses

- cwltool/main.py
- tests/test_make_template.py
This request makes `cwltool --make-template` to support union types.
It includes the following fixes:
- `--make-template` fails with the following message: "IndexError: string index out of range"
- It is caused by calling `CommentedSeq()#insert` with empty comment. `insert` can handle `None` comment but cannot handle empty string comment. I fixed it by checking whether the comment is an empty string or not.
- Even if the above issue is fixed, `cwltool --make-template` does not work with the union type because it try to generate examples for all possible types. This request fixes it by generating an example for the first candidate type
I checked it works with the following CWL document.
- https://zenodo.org/api/files/2422dda0-1bd9-4109-aa44-53d55fd934de/download-sra.cwl
```cwl
...
inputs: …
```
> Fix '--make-template' for union types

- .github/workflows/ci-tests.yml
- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/cwlrdf.py
- cwltool/docker.py
- cwltool/job.py
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/pack.py
- cwltool/process.py
- cwltool/procgenerator.py
- cwltool/update.py
- cwltool/validate_js.py
- cwltool/workflow.py
- tests/test_anon_types.py
- tests/test_examples.py
- tests/test_mpi.py
- tests/test_path_checks.py
- tests/test_streaming.py
- tests/test_tmpdir.py
Fixes https://cwl.discourse.group/t/cannot-get-cwltool-to-run-with-podman-when-step-has-dockerrequirement/711/1
> support podman even when not installed as "docker" alias

- cwltool/main.py
This PR simply moves the sys.exit() call so that users call call run() without exiting. I'm currently copy & pasting the body of run (without the sys.exit call of course), but that isn't ideal.
FYI the reason I'm interested in calling run() is because the normal way of using the cwltool [Python API](https://github.com/common-workflow-language/cwltool#import-as-a-module) does not (easily) allow using all of the CLI arguments. (In particular, --cachedir and --provenance)
> Move sys.exit

- cwltool/argparser.py
- cwltool/cwlrdf.py
- cwltool/main.py
- tests/test_examples.py
- tests/test_iwdr.py
The goal of this PR is to allow users to hide the final output json. For large workflows (particularly workflows with scattering) this can be absolutely massive. If the workflow completes successfully this isn't necessarily a problem. However, if the workflow fails, users will need to scroll up past the final output so they can see the error message(s).
The problem I'm finding is that (despite my urging) users are apparently unable or unwilling to scroll up...
The solution I've chosen here simply adds a CLI flag --no-print-final-output which hides the final output. Note that using --provenance, this information is still available at provenance/workflow/final-output.json
Another solution is instead of using print, the code could use the python logging API. Then developers using the python …
> --write-summary to redirect final JSON output

- .github/workflows/ci-tests.yml
- conformance-test.sh
- release-test.sh
- tests/cwl-conformance/cwltool-conftest.py
1. Usethe `cwltest` plugin for pytest
2. Simplify the Singularity install
3. Simplify the release test
All together this speeds up the entire GitHub Actions CI run.
Previously [29 minutes 22 seconds](https://github.com/common-workflow-language/cwltool/actions/runs/3861522701)
Now [14 minutes 43 seconds](https://github.com/common-workflow-language/cwltool/actions/runs/3874289641)
> conformance testing: switch to pytest + cwltest

- .gitignore
- docs/conf.py
Related to https://github.com/common-workflow-language/user_guide/issues/334
The HTML build of Sphinx creates an inverted list of links (like a hashmap? or a dict), which can be used by extensions like `intersphinx` for linking between Sphinx sites.
In the issue linked, it is not possible to link to the cwltool installation anchor section, as it's not included in the inverted objects list (test with `python -m sphinx.ext.intersphinx https://cwltool.readthedocs.io/en/latest/objects.inv`).
With this change, the anchor items must be unique (I believe they are all unique at the moment, no errors after this change), and they are included in the `.inv` file during the HTML build, and the linked PR can successfully use it as a link.
Cheers
Bruno
> [doc] Add autolabels so intersphinx can link to anchors like index#install

- .github/workflows/ci-tests.yml
- .readthedocs.yml
- Makefile
- README.rst
- cwltool/argparser.py
- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/process.py
- cwltool/singularity.py
- docs/index.rst
- tox.ini
> readthedocs: install graphviz

- release-test.sh
Fix for "AttributeError: module 'importlib.util' has no attribute 'abc'"
Don't isolate the first stage of the build, to keep the version numbers
> bump minimum setuptools version

- cwltool/provenance_profile.py
- tests/test_provenance.py
Changes the code to add a "cwlprov:basename" entry for directories (currently it is only added for files).
This is needed to support reproducibility when directories need to follow a naming pattern (e.g., from `secondaryFiles`).
> CWLProv: add directory basename to the provenance metadata

- cwltool-in-docker.sh
I was working with the `cwltool` container image, and I was wondering if the intent with the `cwltool-in-docker.sh` entrypoint was to raise an error if both the Docker socket is unavailable and `DOCKER_HOST` is unset. I could be completely wrong, but I wanted to check just in case.
> Raise error is socket is **not** available

- cwltool/executors.py
The executor interface is instanced rather than a constructor interface, and the most recent results are saved on the object as final_output and final_status.  We should be able to invoke the executor more than once, however the current executor will not overwrite previously recorded results with new results.  This change clears final_output and final_status each time execute() is called so that new results can be recorded.
> Executor clears any saved result when execute is called.

- cwltool/process.py
- tests/test_examples.py
- tests/wf/resreq_expr_float_v1_0.cwl
- tests/wf/resreq_expr_float_v1_2.cwl
> CWL exprs in ResourceRequirement fields can return floats in CWL v1.2+

- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/context.py
- cwltool/cwlrdf.py
- cwltool/load_tool.py
- cwltool/main.py
- cwltool/pack.py
- cwltool/process.py
- cwltool/procgenerator.py
- cwltool/provenance.py
- cwltool/update.py
- cwltool/validate_js.py
- cwltool/workflow.py
- tests/test_anon_types.py
- tests/test_examples.py
- tests/test_mpi.py
- tests/test_path_checks.py
- tests/test_streaming.py
- tests/test_subclass_mypyc.py
- tests/test_tmpdir.py
Running CWL on windows currently requires Windows Subsystem for Linux, but due to this import statement, windows users who have not yet installed WSL (or cannot install WSL due to administrator privileges) cannot even import most modules.
Since pwd is only used in provenance.py on one line https://github.com/common-workflow-language/cwltool/blob/main/cwltool/provenance.py#L80, guarding the `import pwd` will allow all other use cases that don't involve running with provenance.
> guard `import pwd` for windows

- cwltool/update.py
- tests/test_load_tool.py
- tests/wf/hello-workflow-badhints.cwl
- tests/wf/hello-workflow-badhints2.cwl
Thanks to @sjaenick  for the report
> Better error message when parsing hints in the upgrader

- cwltool/job.py
found while working with @RenskeW
> --leave-tmpdir includes the input staging directories

- cwltool/main.py
- tests/test_provenance.py
- tests/wf/revsort-job-shortcut.json
Fixes: https://github.com/ResearchObject/runcrate/issues/36
> CWLProv snapshots: capture the workflow even if the cwl:tool trick in the input object is used

- Makefile
- cwltool/workflow.py
- requirements.txt
- setup.cfg
- setup.py
- test-requirements.txt
- tox.ini
`setup.py` was missing `importlib_resources` and `importlib_metadata` which broke the last release :-(
> synchronize setup.py & requirements.txt

- cwltool/process.py
- tests/test_relocate.py
- tests/wf/conflict.cwl
This error was found via [@tom-tan 's contribution to cwltest](https://github.com/common-workflow-language/cwltest/commit/4c57396b9063988a296dc99fac5ecf03b2c44302), that actually tested the existence and hashsums of all reported outputs. Thank you @tom-tan !
> Ensure that files with identical basenames get staged to unique paths

- cwltool/job.py
For systems using qemu-user-static to run foreign binaries outside of containers
Description of `QEMU_LD_PREFIX` https://lists.gnu.org/archive/html/qemu-devel/2011-07/msg02389.html
> pass through QEMU_LD_PREFIX by default

- cwltool/command_line_tool.py
- tests/secondary-files-required-container.cwl
- tests/secondary-files-required-missing-container.cwl
- tests/test_docker.py
Fixes https://github.com/common-workflow-language/cwltool/issues/1869
> required outputs with secondaryFiles fix for containers

- .github/workflows/ci-tests.yml
- README.rst
- docs/pythonversions.rst
- setup.py
- refresh python version support
- CI: Drop Python 3.7 from testing
> Update Python version support document; drop Python 3.7 (EOL)

- cwltool/workflow.py
- tests/test_subclass_mypyc.py
Will help with https://github.com/DataBiosphere/toil/issues/4520
> enable pickling of cwltool.workflow.Workflow

- cwltool/job.py
When a podman process finishes even before reaching the monitoring method, a deadlock happens, as no one is updating `process.returncode` and spawned process is in zombie state (so, no signal is sent).
This fix adds a `process.poll()` call, so it gives the chance to fill in `process.returncode`.
Fixes: #1883
> Fixed race condition which happens when a job runs "too fast",

- cwltool/docker.py
- cwltool/job.py
- tests/test_examples.py
- tests/wf/timelimit.cwl
Use docker/podman/udocker inspect to check container images are already in the local registry.
Additionally, removed superfluous udocker/podman pull, which was done even when `--disable-pull` parameter is passed.
This should fix issue #1884
> Propery locate podman images

- cwltool/executors.py
- cwltool/process.py
Hello, 
I have been attempting to execute a CUDA-based workflow using the `--parallel` flag. However, I encountered the following error message:
``` 
ERROR Got workflow error: 'cudaDeviceCount'
File "/home/donyapourn2/actions-runner/_work/workflow-inference-compiler/workflow-inference-compiler/3/envs/globalwic/lib/pypy3.9/site-packages/cwltool/executors.py", line 314, in _runner
job.run(runtime_context, TMPDIR_LOCK)
File "/home/donyapourn2/actions-runner/_work/workflow-inference-compiler/workflow-inference-compiler/3/envs/globalwic/lib/pypy3.9/site-packages/cwltool/job.py", line 823, in run
self._setup(runtimeContext)
File "/home/donyapourn2/actions-runner/_work/workflow-inference-compiler/workflow-inference-compiler/3/envs/globalwic/lib/pypy3.9/site-pack …
```
> add cudaDeviceCount flag to the request requirements

- cwltool/job.py
```
File "/home/jfennick/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/cwltool/job.py", line 518, in get_tree_mem_usage
children = monitor.children()
File "/home/jfennick/mambaforge-pypy3/envs/wic/lib/python3.10/site-packages/psutil/__init__.py", line 277, in wrapper
raise NoSuchProcess(self.pid, self._name, msg=msg)
psutil.NoSuchProcess: process no longer exists (pid=31753)
During handling of the above exception, another exception occurred:
File "/home/jfennick/mambaforge-pypy3/envs/wic/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/home/jfennick/mambaforge-pypy3/envs/wic/lib/python3.10/threading.py", line 1378, in run
self.function(*self.args, **self.kwargs)
File …
```
> use nonlocal mem_tn variable

- .github/workflows/ci-tests.yml
- cwltool/checker.py
- cwltool/context.py
- cwltool/cwlprov/__init__.py
- cwltool/software_requirements.py
- cwltool/utils.py
- docs/conf.py
- gittaggers.py
- pyproject.toml
- requirements.txt
- setup.py
- tox.ini
Galaxy is py3.7+ still, so lets get one last release with some of the latest fixes while we are updating the pending CWL import feature. Hopefully they will move to py3.8+ by the next time we want to update their pin on cwltool
> add back in Python 3.7 for one last release

- release-test.sh
- release: preinstall udocker so that test_udocker_should_display_memory_usage doesn't timeout
- release: testenv4 isn't needed
- release: bump minimum setuptools version slightly to match Debian 11 ('bullseye').
> release testing tweaks

- cwltool/software_requirements.py
- mypy-requirements.txt
- pyproject.toml
- setup.py
- test-requirements.txt
- tests/test_dependencies.py
This reverts commit 9144a780cc5fd62e28b11c059c99e12608135d22.
While we are waiting for https://github.com/galaxyproject/galaxy/pull/16831 to be released
> downgrade galaxy-tool-util to workaround issue with newer conda

- cwltool/context.py
- tests/test_subclass_mypyc.py
Hello, I'm trying to run a CWL workflow using Toil which involves the serialization/pickling of jobs. However the recent updates to CWL throws this stack trace below
``` 
File "/home/donyapourn2/mambaforge-pypy3/envs/toil_test/bin/toil-cwl-runner", line 8, in <module>
sys.exit(main())
File "/home/donyapourn2/mambaforge-pypy3/envs/toil_test/lib/python3.10/site-packages/toil/cwl/cwltoil.py", line 3903, in main
outobj = toil.start(wf1)
File "/home/donyapourn2/mambaforge-pypy3/envs/toil_test/lib/python3.10/site-packages/toil/common.py", line 1406, in start
rootJobDescription = rootJob.saveAsRootJob(self._jobStore)
File "/home/donyapourn2/mambaforge-pypy3/envs/toil_test/lib/python3.10/site-packages/toil/job.py", line 2670, in saveAsRootJob
self._saveJobGraph(jobStore, saveSelf=True)
File …
```
> fix the pickling error for IO objects

- .github/workflows/ci-tests.yml
- .github/workflows/quay-publish.yml
Testing this at https://github.com/common-workflow-language/cwltool/actions/runs/6589494251/job/17904086601
> gh-actions: need newer setuptools to run setuptools_scm

- cwltool/software_requirements.py
- mypy-requirements.txt
- pyproject.toml
- setup.py
- test-requirements.txt
- tests/test_dependencies.py
Skip the known broken versions (23.0.1 - 23.0.5)
> software dependencies: allow newer versions of galaxy-tool-util

- cwltool/pathmapper.py
- cwltool/process.py
Should speed up items_exclude_children() a bit
> pathmapper: don't use temporary lists

- .github/workflows/ci-tests.yml
- .github/workflows/quay-publish.yml
- cwltool/docker.py
- cwltool/singularity.py
- cwltool/udocker.py
- mypy-requirements.txt
- pyproject.toml
- requirements.txt
- setup.py
- tests/test_environment.py
- tests/util.py
Uh-oh, there are 378 CWL v1.2 conformance tests, but only [338 are being run](https://github.com/common-workflow-language/cwltool/actions/runs/6863857026/job/18664447106?pr=1942#step:7:1028) (40 are missing!).
> run the CWL v1.2.1 conformance tests

- cwltool/command_line_tool.py
- cwltool/process.py
- tests/test_examples.py
- tests/wf/extract_region_specs.cwl
Seems to have popped up due to a literal `default` `class: File` inside a CommandLineTool.
> fix compute_checksums during cache check for input File with literal default

- cwltool/job.py
Starting from Podman 4.4.0, cidfile is removed along with the container.
Always return if container is terminated so we don't stuck in the loop waiting for a file which has already been removed.
Fixes: #1961
> Fix fast container job hangs

- cwltool/main.py
- tests/test_main_parsed_args.py
Permit calling `cwltool.main` with preparsed args only, even when requesting provenance.
- Parameter `argsl`, the unparsed arguments, is now optional in `cwltool.setup_provenance`. Since it has a default value it must be moved to the end of the parameter list.
- Unit tests [`test_main_parsed_args`](https://github.com/davidjsherman/cwltool/blob/08e5b9c21e05beb252f9dee2c52ea42550a24063/tests/test_main_parsed_args.py#L10-L21)  and [`test_main_parsed_args_provenance`](https://github.com/davidjsherman/cwltool/blob/08e5b9c21e05beb252f9dee2c52ea42550a24063/tests/test_main_parsed_args.py#L24-L40) verify that `cwltool.main` can be called with parsed arguments only, respectively with and without a request for provenance.
Closes #1963
> Permit calling cwltool.main with preparsed args only even with provenance

- cwltool/singularity.py
If user adds `dockerImageId` along with `dockerFile` , then rename the output image from spython Client.build accordingly
> rename singularity image

- cwltool.Dockerfile
- cwltool/software_requirements.py
- pyproject.toml
Some of the build dependencies appear to be regular dependencies, and do not appear to be required at build time.
This may cause issues in certain specific situations. See this Dockerfile for a minimal reproducible example.
For now, this PR simply removes galaxy-tool-util from pyproject.toml (only).
```
FROM condaforge/miniforge3
RUN conda install "python<3.10" pypy
RUN conda install psutil
RUN conda install git
RUN pip install cwltool@git+https://github.com/common-workflow-language/cwltool.git
```
> remove galaxy-tool-util from build dependency

- tests/loop/scatter-inside-loop.cwl
- tests/test_loop.py
This PR adds a new unit test using scatter and loop features in the workflow. In particular, it is tested if a scatter step works well inside a loop. Before this PR, only the "loop inside scatter" case was checked.
> Added new test on loop

- cwltool/cwlprov/provenance_profile.py
- cwltool/docker.py
- cwltool/extensions-v1.1.yml
- cwltool/extensions-v1.2.yml
- cwltool/extensions.yml
- cwltool/process.py
- cwltool/singularity.py
- tests/test_docker.py
- tests/wf/shm_size.cwl
Fixes #1821  
https://github.com/common-workflow-language/cwltool/issues/1821#issuecomment-1481347082
> add the --shm-size parameter at runtime

- conformance-test.sh
- release-test.sh
- test-requirements.txt
- tox.ini
Hopefully this speeds up CI on GH-Actions
> pytest: use the worksteal scheduler and run on all logical cores, not just physical.

- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/cwlrdf.py
- cwltool/docker.py
- cwltool/utils.py
- tests/test_path_checks.py
This is because some bytes-like objects (such as memoryview) don't have a "decode()" method.  It appears that the preferred way to get a decoded string is to simply call the constructor with the bytes-like object and the desired encoding.
> Replace .decode method with str(bytes, "utf-8")

- cwltool/docker.py
- tests/test_tmpdir.py
Don't let dockerFile tag be dependent on force_pull or pull_image booleans
> patch dockerFile build

- cwltool/cwlprov/ro.py
I've added a few docstrings to `ro.py` that were missing. 
This is my first PR here. Any feedback is welcome!
> Add docstrings to functions in `ro.py`

- .github/workflows/ci-tests.yml
- conformance-test.sh
- cwltool/builder.py
- cwltool/command_line_tool.py
- cwltool/cwlprov/ro.py
- cwltool/cwlrdf.py
- cwltool/docker.py
- cwltool/utils.py
- lint-requirements.txt
- mypy-requirements.txt
- pyproject.toml
- release-test.sh
- setup.py
- test-requirements.txt
- tests/test_path_checks.py
- tests/test_tmpdir.py
sync with main while working on prov branch
> Update branch to sync with main

- cwltool/job.py
> Support Podman version 5.x which autodeletes the cidfiles

- tests/loop/opt-var-loop.cwl
- tests/test_loop.py
This commit adds a new test checking optional input variable of a step inside a loop case.
>  Added new loop test

- README.rst
> removing duplicate "reference"

- cwltool/argparser.py
- tests/test_toolargparse.py
It fixes #2034 by considering the case of arrays of integers and floating point numbers.
> Support array of integers and floats as command argument parameters

- cwltool/checker.py
- cwltool/errors.py
- cwltool/schemas/v1.3.0-dev1/Workflow.yml
- cwltool/update.py
- cwltool/workflow_job.py
- tests/loop/all-output-loop-no-iteration.cwl
- tests/loop/all-output-loop.cwl
- tests/loop/default-value-loop.cwl
- tests/loop/invalid-loop-scatter.cwl
- tests/loop/invalid-loop-when-exception.cwl
- tests/loop/invalid-loop-when-exception2.cwl
- tests/loop/invalid-multi-source-loop-no-requirement.cwl
- tests/loop/invalid-no-loopWhen.cwl
- tests/loop/invalid-non-boolean-loopWhen.cwl
- tests/loop/invalid-non-boolean-loopWhen2.cwl
- tests/loop/invalid-value-from-loop-no-requirement.cwl
- tests/loop/loop-inside-loop-all.cwl
- tests/loop/loop-inside-loop.cwl
- tests/loop/loop-inside-scatter.cwl
- tests/loop/multi-source-loop.cwl
- tests/loop/opt-var-loop.cwl
- tests/loop/scatter-inside-loop.cwl
- tests/loop/single-var-loop-no-iteration.cwl
- tests/loop/single-var-loop.cwl
- tests/loop/two-vars-loop-2.cwl
- tests/loop/two-vars-loop.cwl
- tests/loop/value-from-loop.cwl
- tests/test_loop.py
- tests/test_path_checks.py
Updated `outputMehtod` values to `last_iteration` and `all_iterations`, according to common-workflow-language/cwl-v1.3#5.
> Updated `outputMethod` values

- cwltool/singularity.py
- tests/test_environment.py
Context for the PR:
Currently if the user uses a `docker` image in a workflow and depending on the choice of the container engine (`docker` vs `singularity`), the execution can be different, if the `docker` image has an entrypoint. 
I understand that CWL community encourages docker images w/o entrypoints, however there are a good number of images produced by various scientific communities that comes with entrypoints. When this images are used in HPC environment, in most cases, due to security policies (not having access to `root`), `singularity` is chosen as the container engine. In these cases, `docker` images with entrypoint fails to execute. 
I also know that creating `CommandLineTools` with a `baseCommand` can bypass the entrypoint issue when running with `singularity` but that also …
> Use "run" with singularity/apptainer instead of "exec", when possible

- cwltool/loghandler.py
- cwltool/main.py
- tests/test_examples.py
- tests/test_validate.py
- tests/util.py
> `--no-warnings` includes schema-salad; `--validate` should complain to stdout

- cwltool/extensions-v1.2.yml
This commit fixes two small errors in the `cwltool:Loop` definition that were breaking the Schema SALAD codegen procedure.
> Fix `cwltool:Loop` extension definition

- .github/workflows/ci-tests.yml
- cwltool/argparser.py
- cwltool/main.py
- pyproject.toml
- requirements.txt
- setup.py
- tests/test_environment.py
- tests/test_misc_cli.py
- tests/test_singularity.py
Makes the [argument groups](https://docs.python.org/3/library/argparse.html#argument-groups) really stand out
Example of `cwltool --help` colored output.
Example of `cwltool tests/CometAdapter.cwl --help`
> argparse: colorize the `--help` output with rich-argparse

- cwltool/command_line_tool.py
- cwltool/pathmapper.py
- tests/iwdr_writable_secfile-inputs.json
- tests/iwdr_writable_secfile.cwl
- tests/test_iwdr.py
Fixes: https://github.com/common-workflow-language/cwltool/issues/2131
> propagate writable attribute to secondaryfiles

- cwltool/builder.py
- cwltool/main.py
- cwltool/software_requirements.py
From 1.84user 0.18system 0:02.03elapsed to 0.71user 0.11system 0:00.83elapsed for `cwltool --help`
> 2X faster startup, defer galaxy-* imports to when needed
